### ISSUE TITLE
ERROR: for bigchaindb_bigchaindb_1  Cannot start service bigchaindb: OCI runtime create failed:

### ISSUE THREAD

**Issue by spider-hand** [bigchaindb/bigchaindb#2194] opened 2018-04-12 06:16 UTC
I was trying to start bigchaindb and this error occured when I did `make run`.
The whole error message is here

```
INFO:bigchaindb.config_utils:Cannot find config file `/root/.bigchaindb`.
Generating default configuration for backend localmongodb
Configuration written to /root/.bigchaindb
Ready to go!
Removing intermediate container 9d4aa0c6934e
 ---> 9a83ebfbb983
Successfully built 9a83ebfbb983
Successfully tagged bigchaindb_bigchaindb:latest
WARNING: Image for service bigchaindb was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating bigchaindb_tendermint_1 ... done
Creating bigchaindb_mongodb_1    ... done
Creating bigchaindb_bigchaindb_1 ... error

ERROR: for bigchaindb_bigchaindb_1  Cannot start service bigchaindb: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/c/Users/akino/Downloads/bigchaindb/tox.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/9f3f5f3b08ce22bcc62bb48eb3f7e86b687348749101c16c37266ac5cb6066a0/merged\\\" at \\\"/var/lib/docker/overlay2/9f3f5f3b08ce22bcc62bb48eb3f7e86b687348749101c16c37266ac5cb6066a0/merged/usr/src/app/tox.ini\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for bigchaindb  Cannot start service bigchaindb: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/c/Users/akino/Downloads/bigchaindb/tox.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/9f3f5f3b08ce22bcc62bb48eb3f7e86b687348749101c16c37266ac5cb6066a0/merged\\\" at \\\"/var/lib/docker/overlay2/9f3f5f3b08ce22bcc62bb48eb3f7e86b687348749101c16c37266ac5cb6066a0/merged/usr/src/app/tox.ini\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
Makefile:59: recipe for target 'run' failed
make: *** [run] Error 1
```

I'm using WSL which is connected to Docker on Windows.
How can I fix this error?

**Comment by ttmc** [comment] 2018-04-12 09:44
If I had to guess, I'd guess the problem is WSL, Docker on Windows, or their combination. We generally run everything on actual Linux machines or VMs.

**Comment by vrde** [comment] 2018-04-18 14:12
@spider-hand can you retry with the latest master? There were some problems with `docker-compose.yml` that should be fixed now.

**Comment by spider-hand** [comment] 2018-04-25 20:31
Hi, still the same error happens.

**Comment by ttmc** [comment] 2018-08-21 08:46
This is an old issue, on an unsupported operating system, so I'm closing it.

**Closed by ttmc** 2018-08-21 08:46 UTC

**Comment by KevinBaylor** [comment] 2019-04-15 01:02
Please tell me how can a Linux VM user run bigchaindb?

**Comment by ttmc** [comment] 2019-04-15 07:24
@KevinBaylor Please read the docs, e.g. http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/index.html
