### ISSUE TITLE
Error:- cannot import name 'bigchain'

### ISSUE THREAD

**Issue by sugandhasingla** [bigchaindb/bigchaindb#1287] opened 2017-03-15 12:13 UTC
<img width="662" alt="screen shot 2017-03-15 at 5 34 11 pm" src="https://cloud.githubusercontent.com/assets/9273762/23947946/ddeca812-09a6-11e7-9fd8-e9f12e06e3c8.png">

**Comment by TimDaub** [comment] 2017-03-15 14:20
Hi @sugandhasingla,


thanks for your interest in BigchainDB.
I can't see the specific problem yet but here are a few tips that might help you resolve the issue:

1. Do you use a virtual environment? If not, I highly recommend setting one up to start and work with BigchainDB.
2. We don't officially support BigchainDB running on Mac OS X. We usually point Mac users to our documentation on how to run BigchainDB with docker: https://docs.bigchaindb.com/projects/server/en/latest/appendices/run-with-docker.html
3. It seems that your BigchainDB instance is not able to connect to MongoDB or RethinkDB (`Can't connect to ('localhost', 9984)`). Make sure you have one of those running in another tab. If you do and it still doesn't connect: Try to adjust BigchainDB's configuration paramters. Since you should be using docker under Mac OS X though, it would take care of running and configuring both correctly.
4. You're using BigchainDB version 0.9.0.dev. This is not a version that we officially support. It's just used to develop the software internally. Try using the latest 0.9.3 release from DockerHub or Pypi.

Please let me know if any of those tips resolved the problem.

**Comment by sugandhasingla** [comment] 2017-03-17 16:44
Hey Tim
Thanks for the quick reply. We actually have updated bigchainDB to 0.9.4 version. We are trying to connect to bigchaindb address:- from bigchaindb_driver import BigchainDB
bdb = BigchainDB('http://localhost:9984'). 

Can you please help? Thanks a lot

![pasted image at 2017_03_17 09_40 am](https://cloud.githubusercontent.com/assets/9273762/24053457/2060f7c0-0b5f-11e7-9ea5-da67898353c9.png)


![pasted image at 2017_03_17 09_38 am](https://cloud.githubusercontent.com/assets/9273762/24053425/0a891ad6-0b5f-11e7-9528-a355d6e8de6c.png)

![pasted image at 2017_03_17 09_39 am](https://cloud.githubusercontent.com/assets/9273762/24053440/1544281c-0b5f-11e7-90ab-5f124533d4a5.png)

**Comment by sbellem** [comment] 2017-03-17 17:19
Hi @sugandhasingla, although it may not be the root cause of your problem, it is important to notice that the Python driver for BigchainDB requires Python 3.5 or higher.

**Comment by sbellem** [comment] 2017-03-17 18:28
It looks like you are running the BigchainDB server in a docker container. In that case, assuming you are running it via the command:

```bash
docker run \
  --name=bigchaindb \
  --publish=9984:9984 \
  --restart=always \
  --volume=$HOME/bigchaindb_docker:/data \
  bigchaindb/bigchaindb \
  start
```

could you try adding the following environment variable `BIGCHAINDB_SERVER_BIND` to `0.0.0.0:9984`? You could do so this way:

```
docker run \
  --name=bigchaindb \
  --publish=9984:9984 \
  --restart=always \
  --volume=$HOME/bigchaindb_docker:/data \
  --env BIGCHAINDB_SERVER_BIND=0.0.0.0:9984
  bigchaindb/bigchaindb \
  start
```

Let us know if that helps. In any case you need to make sure you can access the container where the BigchainDB server is running. When using the driver, you check your connection in a simple way:

```python
>>> bdb = BigchainDB('http://localhost:9984')
>>> bdb.info()
{'_links': {'api_v1': 'http://localhost:9984/api/v1/',
  'docs': 'https://docs.bigchaindb.com/projects/server/en/0.9/'},
 'keyring': [],
 'public_key': 'GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4',
 'software': 'BigchainDB',
 'version': '0.9.4'}
```

**Comment by r-marques** [comment] 2017-03-30 08:49
@TimDaub can we close this?

**Comment by TimDaub** [comment] 2017-03-30 09:10
@r-marques Thx for pointing this out.

@sugandhasingla We'll close this ticket for now. If you're still having problems, feel free to reach out and we'll reopen this ticket and try to help you.

**Closed by TimDaub** 2017-03-30 09:10 UTC
Labels: BUG
