### ISSUE TITLE
Inconsistent stack.sh script 

### ISSUE THREAD

**Issue by ashishkshukla** [bigchaindb/bigchaindb#2363] opened 2018-06-28 12:14 UTC
OS- CentOS 7.2

I am trying to setup the 4 node BigchainDB Network by following document .
https://docs.bigchaindb.com/projects/contributing/en/latest/dev-setup-coding-and-contribution-process/run-dev-network-stack.html#stack-type-docker

In the document it is mentioned that one should have CenOS version 7 or later.

when I run the script, I get the exception like below
```
: MINIMUM_CENTOS_VERSION: unbound variable
Unsupported centos Version: 7
```

Attaching screenshot for the reference.
<img width="847" alt="bigchaindb_docker_issue" src="https://user-images.githubusercontent.com/3691950/42033445-88421dd6-7afa-11e8-9b6f-03740307115b.PNG">

**Comment by muawiakh** [comment] 2018-06-28 12:41
@ashishkshukla I have pushed a fix for the problem you were facing. It might save some of your time if you just checkout out the changes at #2364 and apply them inside the `bigchaindb` cloned by `stack.sh` (same directory). Let me know if it works and feel free to close if the issue is resolved after that.

**Comment by muawiakh** [comment] 2018-06-28 12:45
Re-opening for @ashishkshukla to confirm resolution. Since the changes are merged, you can also delete the `bigchaindb` cloned by `stack.sh` and re-run `stack.sh`.

**Comment by ashishkshukla** [comment] 2018-06-28 13:12
@muawiakh this problem seems to be fixed. This issue can be closed.

**Closed** 2018-06-29 07:22 UTC
Labels: deployment
