### ISSUE TITLE
Cannot use BigchainDB with MongoDB hosted solutions such as CosmosDB

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1838] opened 2017-11-13 10:34 UTC
### Problem
Cannot use BigchainDB with MongoDB hosted solutions such as CosmosDB.

BigchainDB checks whether MongoDB was started with some command line option to see whether a replica set is used, instead of using https://docs.mongodb.com/manual/reference/command/replSetGetConfig/

**Comment by muawiakh** [comment] 2017-11-16 17:26
I think the issue is invalid, we do expect `MongoDB` to be started with a replica set command line flag or via the configuration file, but that is a requirement for MongoDB. According to the MongoDB documentation, if you want to deploy a replica set, you MUST specify replication specific parameters i.e. `--replset` (on Command line) OR `replication.replSetName` (configuration file). This configuration is the name of the replica set that the [mongod](https://docs.mongodb.com/manual/reference/program/mongod/#bin.mongod) will be a part of and all hosts in the replica set must have the same name, and you cannot initialize a replicaSet if you do not specify these options. For reference, refer to the following [document](https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/#convert-a-standalone-to-a-replica-set), which converts a standalone mongod instance into a replica set member, essentially what they do is that, they restart the mongod process and specify the above mentioned configuration.

Here is the reference to the official MongoDB documentation on how to initiate a replica set: https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

The document specified in the ticket is just the command which returns a document describing the state of your replica set. So, I don't know how that is relevant.

One thing, I can point to is the way be initialize the replica set in our [production deployment template](https://docs.bigchaindb.com/projects/server/en/latest/production-deployment-template/node-on-kubernetes.html), i.e. we configure the MongoDB replica set member before starting BigchainDB(so BigchainDB does not have to initialize the replica set). If that helps.

Meanwhile, closing this ticket. We can re-open, if my understanding is not correct.

**Closed** 2017-11-16 17:26 UTC
Labels: BUG
