### ISSUE TITLE
rename `get_owned_ids` to `get_unspents`

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#603] opened 2016-08-26 13:23 UTC
more universal lingo

**Comment by amrandahvur** [comment] 2016-10-12 18:40
Please Assign me this

**Comment by ttmc** [comment] 2016-10-13 07:24
Hacktoberfest aside, this issue needs to be revisited so that `get_owned_ids` is renamed something consistent with the new names of `owners_before` and `owners_after`: see https://github.com/bigchaindb/bigchaindb/issues/626

My inclination is to close this issue and bundle it with #626

**Comment by diminator** [comment] 2016-10-13 07:44
> this issue needs to be revisited so that get_owned_ids is renamed something consistent with the new names of owners_before and owners_after

The `get_owned_ids` function is meant to check what you have in your current wallet, the things you haven't spent yet. This way you can compute your balance. `unspents` is common language in cryptocurrency space, see [here](https://bitcoin.org/en/glossary/unspent-transaction-output)

My take is that we use "known" language for such API functions, and it's agnostic to the implementation under the hood

**Comment by ttmc** [comment] 2016-10-13 08:30
The problem is, a BigchainDB instance doesn't know the assets _owned_ by a public key. The so-called `owners_after` and `owners_before` lists are not lists of asset owners; they are lists of public keys which have (or had) the ability to enable a transfer. (This is why we want to rename those lists as per issue #626.)

If someone wants to get a list of the assets they own (in a particular BigchainDB database), then they are out of luck. Asset _owners_ aren't stored in BigchainDB, only transfer-enablers / signers / fulfillers / controllers / (whatever we decided to call them).

That function, `get_owned_ids` _will_ return a list of unspent assets associated with a particular key, so `get_unspents` is probably okay. One must be very careful not to interpret those assets as being owned by the key (or keyholder). I worry that this will be a source of confusion and a common source of human error.

**Comment by diminator** [comment] 2016-10-13 08:35
see the comments in #677

**Comment by ttmc** [comment] 2016-10-24 07:23
1. `get_unspents` is fine, but
2. the docstring and implementation of that method (in `bigchaindb/bigchaindb/core.py`) must be modified so that users of that method can correctly interpret what it _actually_ returns.

**Comment by sbellem** [comment] 2016-10-24 15:31
> Change the input parameter from owner to pubkey
> Say that the output is a list of unspent outputs (TransactionLinks, i.e. txid + cid pairs) associated with that pubkey
> Rename the internal variable owned to txlinks or similar

we could turn this into tasks?

**Comment by ttmc** [comment] 2016-10-25 08:53
@sbellem Okay I changed those to tasks.

**Comment by sbellem** [comment] 2016-10-25 13:20
### Naming convention: public/private keys versus verifying/signing keys
This question could perhaps have its own issue, but I'll ask here, and we can create an issue if needed.

I simply wonder whether we should stick to one rather than using both interchangeably. It may help make the code simpler, especially for new comers.

**Comment by r-marques** [comment] 2016-10-25 13:43
Looking at the literature they seem to be used interchangeably.

In asymmetric cryptography algorithms that provide both signing and encryption they use the terms public/private key.
For asymmetric cryptography algorithms that only provide signing like ed25519 they sometimes refer to the keys as signing/verifying key.

It seems that public/private keys is a more universal term. But at the same time is always advisable to use different keys for signing and encryption and in that case a distinction between public/private and signing/verifying would be desirable.

At this point we only use the keys for signing and verifying maybe we could switch to using public/private everywhere since its the most used term

**Comment by ttmc** [comment] 2016-10-25 15:35
@sbellem and @r-marques It would be nice for us all to agree on a convention for what to call the keys (public/private versus verifying/signing), but that should be a separate issue. I will create one...

**Comment by sbellem** [comment] 2016-10-25 16:36
@ttmc @r-marques

Out of curiosity, if we were to use the terms signing key and verifying key, then would it be more accurate to rename `owner` to `verifying_key`, or some short form, e.g.: `vk`, `verifkey`?

**Comment by ttmc** [comment] 2016-10-26 08:40
@sbellem Yes, if we do decide to use "verifying key" across the board, then it would be better to use `vk` or `verifkey` or whatever as the replacement of `owner`.

Today, we use `pubkey` in some code and `vk` or similar in other code. It's a bit of a mess. Hence the need for a separate issue, which is why I created issue #746. This issue is mostly about renaming `get_owned_ids` to `get_unspents`.

**Comment by sbellem** [comment] 2016-10-26 09:51
@ttmc ah ok, thanks! Should we decide on #746 before, to avoid renaming?

**Comment by ttmc** [comment] 2016-10-26 15:37
@sbellem Whoever does #746 is going to have to rename a bunch of stuff all over the place, so it doesn't matter if this issue or that one gets done first.

**Closed** 2018-03-13 15:08 UTC
Labels: easy, topic: SEC core consensus, topic: UX docs cmd api driver
