### ISSUE TITLE
Problem with docker-compose.yml (Chrome: Connection was reset)

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1443] opened 2017-04-26 09:49 UTC
The problem was reported via Gitter by @michielmulders. 

It is not clear what the problem is. Here is the conversation that happened on Gitter:

@michielmulders
> Hii guys, I saw there were some problems with the docker file? I clones https://github.com/bigchaindb/bigchaindb and ran the command 'docker-compose up'. Everything seems to be running but I can't access my API of bigchaindb with port forwarding (9984 or 32772 or 32768, I tried many ports, none of them gave me access). It is strange that my browser says that the connection was reset if I try to access the API over one of these ports. Is there a solution or does someone how to access the API?

@sbellem:
> If you are using the docker-compose.yml file that is under https://github.com/bigchaindb/bigchaindb/blob/master/docker-compose.yml then most ports are not pinned as we use this compose file for development mainly at the moment and port clashes can happen easily ottherwise
you can run the command docker-compose ps to see the port mappings

> Not sure if I answered your question though, so please let me know whether we are talking about the same thing. :grinning:

@michielmulders:
> I checked the port mappings with docker-compose ps but still no luck after trying them all. But if I try one of these ports, I get a message from Chrome saying 'Connection was reset', strange! I saw that someone else is having problems as well with the docker image (20 messages earlier)? Do you have other suggestions?

@sbellem
> Oh ok. Can we move the conversation to a github issue? It will be easier to keep track of related details. Just to be sure, are you using the latest master?

@michielmulders
> I did a docker pull bigchaindb/bigchaindben kreeg dit als resultaat Status: Image is up to date for bigchaindb/bigchaindb:latest and got this as a result : Status: Image is up to date for bigchaindb/bigchaindb:latest

@ttmc
> bigchaindb/bigchaindb:latest is the 0.10 branch, not the master branch (see https://hub.docker.com/r/bigchaindb/bigchaindb/~/settings/automated-builds/ ), but there's probably not much difference between the two right now. You can get the master branch using the label bigchaindb/bigchaindb:master

@sbellem
> the Dockerfile and the docker-compose.yml are two different things and currently the docker-compose.yml -- because it is meant to be used for development -- does not rely on the Dockerfile
By master I was referring to the branch of the repository https://github.com/bigchaindb/bigchaindb you cloned

> It will be easier for us to help you if we move the discussion to a github issue where you document all the details (version, files, etc)

**Comment by michielmulders** [comment] 2017-04-26 11:30
Hi guys, I follow this tutorial now: https://docs.bigchaindb.com/projects/server/en/latest/appendices/run-with-docker.html and used the RethinkDB setup. I can access rethinkdb on virtual address 172.17.0.1:58080 but I can't access the bigchaindb api on 0.0.0.0:59984 

![docker-compose-ps](https://cloud.githubusercontent.com/assets/26482710/25432384/83e4f2da-2a84-11e7-87a0-8ec9dec1a284.png)

![docker ps](https://cloud.githubusercontent.com/assets/26482710/25432383/83d87e60-2a84-11e7-8397-57828867423b.png)


PS: I can't access this link: https://hub.docker.com/r/bigchaindb/bigchaindb/~/settings/automated-builds/

**Comment by sbellem** [comment] 2017-04-26 11:34
@michielmulders thanks for the report! We'll get back to you asap!

**Comment by krish7919** [comment] 2017-04-26 11:46
@michielmulders I have a similar configuration file as you do.
I just pulled the docker images for `rethinkdb:2.3` and `bigchaindb/bigchaindb` (which defaults to the latest releast `bigchaindb/bigchaindb:0.10.1`.

Can you please paste the output of `docker images` too?
I tried the docs and I have this output:
```
$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
rethinkdb               2.3                 c5ed876750b4        31 hours ago        183MB
bigchaindb/bigchaindb   latest              7a8e8503e556        6 days ago          765MB
```

**Comment by michielmulders** [comment] 2017-04-26 12:11
@krish7919 Docker images:
![docker images](https://cloud.githubusercontent.com/assets/26482710/25433837/32a5150c-2a8a-11e7-8a67-33a40f2f2ae6.png)

**Comment by krish7919** [comment] 2017-04-26 12:14
@michielmulders : When you say you cannot access bigchaindb at `0.0.0.0:59984`, can you elaborate on how are you trying to access it?
Using curl or the browser?

**Comment by michielmulders** [comment] 2017-04-26 12:19
@krish7919 I tried to access it first through browser, I was expecting that I would be redirected to `0.0.0.0:59984/api/v1/`. 
Next, I tried this commando to see if I can connect to the port: `nc -zv 0.0.0.0 59984` with as result `Connection to 0.0.0.0 59984 port [tcp/*] succeeded!'

**Comment by krish7919** [comment] 2017-04-26 12:21
@michielmulders I am guessing that you have done everything fine during the setup. Nothing interesting pops up above.
Can you access bigchaindb on `localhost:59984` on the browser or try `curl -X GET http://localhost:59984` locally?

**Comment by michielmulders** [comment] 2017-04-26 12:31
@krish7919 `curl -X GET http://localhost:59984` results in `curl: (56) Recv failure: Connection reset by peer`

**Comment by krish7919** [comment] 2017-04-26 12:35
That's weird. Can you paste the logs from `docker logs -f bigchaindb` and output of `docker version`?
We would need to dig deeper here and find out what could have failed.

**Comment by michielmulders** [comment] 2017-04-26 12:39
`docker version` -->
`Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

It's strange that the logs show entries from timestamp 10:57 AM, however it's now 2PM in my timezone. 
`docker logs -f bigchaindb` -->
`INFO:bigchaindb.config_utils:Configuration loaded from `/data/.bigchaindb`
[2017-04-26 10:57:34] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 0.10.1 (MainProcess - pid: 1)
[2017-04-26 10:57:54] [WARNING] (bigchaindb.backend.connection) Attempt 1/3. Connection to 172.17.0.1:28015 failed after 5000ms. (MainProcess - pid: 1)
[2017-04-26 10:58:14] [WARNING] (bigchaindb.backend.connection) Attempt 2/3. Connection to 172.17.0.1:28015 failed after 5000ms. (MainProcess - pid: 1)
[2017-04-26 10:58:34] [WARNING] (bigchaindb.backend.connection) Attempt 3/3. Connection to 172.17.0.1:28015 failed after 5000ms. (MainProcess - pid: 1)
[2017-04-26 10:58:34] [CRITICAL] (bigchaindb.backend.connection) Cannot connect to the Database. Giving up. (MainProcess - pid: 1)`

**Comment by krish7919** [comment] 2017-04-26 12:42
@michielmulders : It looks like BigchainDB has not connected to the RethinkDB instance from the logs above. I do not know if the time difference can cause an issue here.

Can you paste the output of `docker logs rethinkdb` and then restart the BigchainDB instance.

**Comment by michielmulders** [comment] 2017-04-26 12:48
@krish7919 This is the output of rethink docker logs
![dockerlogsrethinkdb](https://cloud.githubusercontent.com/assets/26482710/25435088/2ffc79d0-2a8f-11e7-9dc6-cbf7dc67ff51.png)

Do you want me to restart with `docker restart (containerID)` ?

**Comment by krish7919** [comment] 2017-04-26 12:53
@michielmulders Those logs never say that a rethinkdb driver has connected to it. So we knowthe root cause now: The BigchainDB server never connected to the RethinkDB instance.

You can restart the BigchainDB container by simply stopping the container and starting it again.
I would suggest following the docs for the commands for starting both the containers.

**Comment by michielmulders** [comment] 2017-04-26 13:13
@krish7919 Stopped everything, restarted rethinkdb, waited one minute and started bigchaindb, still not possible to connect to each other.

**Comment by krish7919** [comment] 2017-04-26 13:17
@michielmulders Let us try to repro this again and get back to you on this one.

Can you provide your environment details till then - OS version and output of `ifconfig` command to see how networking is set up by docker?
Thanks for the info again.

**Comment by michielmulders** [comment] 2017-04-26 13:28
OS version: 
`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial`

IFCONFIG:
`br-21541edf2536 Link encap:Ethernet  HWaddr 02:42:34:9c:68:41  
          inet addr:172.19.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

br-3f197ef439d0 Link encap:Ethernet  HWaddr 02:42:d8:de:39:12  
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

br-be07fee7a386 Link encap:Ethernet  HWaddr 02:42:2b:65:bd:60  
          inet addr:172.20.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker0   Link encap:Ethernet  HWaddr 02:42:ad:1e:8c:73  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:adff:fe1e:8c73/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5302 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6899 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:427189 (427.1 KB)  TX bytes:1262108 (1.2 MB)

enp4s0    Link encap:Ethernet  HWaddr 44:8a:5b:46:f0:e4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:19 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:279655 errors:0 dropped:0 overruns:0 frame:0
          TX packets:279655 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:22573373 (22.5 MB)  TX bytes:22573373 (22.5 MB)

veth4b4c2ad Link encap:Ethernet  HWaddr be:4b:ff:ea:88:2e  
          inet6 addr: fe80::bc4b:ffff:feea:882e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:27 errors:0 dropped:0 overruns:0 frame:0
          TX packets:268 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1938 (1.9 KB)  TX bytes:36028 (36.0 KB)

veth951a827 Link encap:Ethernet  HWaddr 06:4d:c6:7f:30:cb  
          inet6 addr: fe80::44d:c6ff:fe7f:30cb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:37 errors:0 dropped:0 overruns:0 frame:0
          TX packets:527 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3581 (3.5 KB)  TX bytes:75082 (75.0 KB)

wlp5s0    Link encap:Ethernet  HWaddr 80:19:34:62:f5:ac  
          inet addr:10.1.15.101  Bcast:10.1.15.127  Mask:255.255.255.128
          inet6 addr: fe80::20de:aa07:d1c5:e076/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2317464 errors:0 dropped:0 overruns:0 frame:0
          TX packets:158622 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:923026570 (923.0 MB)  TX bytes:26519562 (26.5 MB)`

Environment variables (might be useful):
`XDG_SEAT=seat0
XDG_SESSION_ID=c2
LC_IDENTIFICATION=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
DISPLAY=:0
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
UPSTART_JOB=unity7
JOB=unity-settings-daemon
GNOME_KEYRING_CONTROL=
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
QT_QPA_PLATFORMTHEME=appmenu-qt5
LOGNAME=michiel
INSTANCE=
LC_TIME=fr_FR.UTF-8
SHELL=/bin/zsh
PATH=/home/michiel/.local/share/umake/bin:/home/michiel/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LC_NUMERIC=fr_FR.UTF-8
LC_PAPER=fr_FR.UTF-8
IM_CONFIG_PHASE=1
QT4_IM_MODULE=xim
CLUTTER_IM_MODULE=xim
XMODIFIERS=@im=ibus
SESSION=ubuntu
XDG_MENU_PREFIX=gnome-
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XAUTHORITY=/home/michiel/.Xauthority
XDG_SESSION_DESKTOP=ubuntu
GDMSESSION=ubuntu
UPSTART_EVENTS=xsession started
LC_MEASUREMENT=fr_FR.UTF-8
QT_IM_MODULE=ibus
LC_ADDRESS=fr_FR.UTF-8
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/2292
DESKTOP_SESSION=ubuntu
XDG_RUNTIME_DIR=/run/user/1000
GTK_IM_MODULE=ibus
USER=michiel
GTK_MODULES=gail:atk-bridge:unity-gtk-module
PWD=/home/michiel
VTE_VERSION=4205
LC_MONETARY=fr_FR.UTF-8
UPSTART_INSTANCE=
HOME=/home/michiel
QT_ACCESSIBILITY=1
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
LANGUAGE=en_US
COMPIZ_BIN_PATH=/usr/bin/
COMPIZ_CONFIG_PROFILE=ubuntu
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/michiel
LANG=en_US.UTF-8
GTK2_MODULES=overlay-scrollbar
LC_NAME=fr_FR.UTF-8
GPG_AGENT_INFO=/home/michiel/.gnupg/S.gpg-agent:0:1
SHLVL=1
WINDOWID=98566150
GDM_LANG=en_US
XDG_VTNR=7
TERM=xterm-256color
SESSIONTYPE=gnome-session
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-MWsxhjx4pj
XDG_CURRENT_DESKTOP=Unity
GNOME_KEYRING_PID=
SESSION_MANAGER=local/michiel:@/tmp/.ICE-unix/2518,unix/michiel:/tmp/.ICE-unix/2518
XDG_SESSION_TYPE=x11
OLDPWD=/home/michiel
ZSH=/home/michiel/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_CTYPE=en_US.UTF-8
_=/usr/bin/printenv`

**Comment by krish7919** [comment] 2017-05-02 08:56
Hi @michielmulders : I looked into this issue over the weekend.
I can find nothing wrong with your configuration.
I do see that you have 3 other bridge adapters other than the docker bridge on your system.
Could they be causing the issue?

**Comment by michielmulders** [comment] 2017-05-02 11:31
@krish7919 I took the br-* bridges down. 
Next, I removed all containers and images and downloaded them again.
I followed the configuration steps on the website and waited 10min before starting bigchaindb after rethinkdb was started. 

It created 2 bridges: vethed78b02 and veth24ea235 , is this correct? So can it be a problem with bridges? I took the other 3 bridges down with the command 'sudo ifconfig br-* down'

`docker0   Link encap:Ethernet  HWaddr 02:42:f3:ec:d9:d9  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:f3ff:feec:d9d9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7096 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7918 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1286851 (1.2 MB)  TX bytes:47807375 (47.8 MB)

enp4s0    Link encap:Ethernet  HWaddr 44:8a:5b:46:f0:e4  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:19 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:69341 errors:0 dropped:0 overruns:0 frame:0
          TX packets:69341 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:3469994 (3.4 MB)  TX bytes:3469994 (3.4 MB)

veth24ea235 Link encap:Ethernet  HWaddr 4e:aa:d5:34:be:49  
          inet6 addr: fe80::4caa:d5ff:fe34:be49/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1581 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1705 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:153702 (153.7 KB)  TX bytes:341197 (341.1 KB)

vethed78b02 Link encap:Ethernet  HWaddr de:9c:54:25:68:f8  
          inet6 addr: fe80::dc9c:54ff:fe25:68f8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14 errors:0 dropped:0 overruns:0 frame:0
          TX packets:44 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1060 (1.0 KB)  TX bytes:5719 (5.7 KB)

wlp5s0    Link encap:Ethernet  HWaddr 80:19:34:62:f5:ac  
          inet addr:10.1.15.50  Bcast:10.1.15.127  Mask:255.255.255.128
          inet6 addr: fe80::20de:aa07:d1c5:e076/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:437693 errors:0 dropped:0 overruns:0 frame:0
          TX packets:97318 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:573196867 (573.1 MB)  TX bytes:12449314 (12.4 MB)`

Docker logs still saying that they can't connect to each other. Is there a way to run them somewhere online in a cloud? I will also try to run it in a virtual Ubuntu Machine, maybe some better luck there.

**Comment by krish7919** [comment] 2017-05-02 11:48
> Docker logs still saying that they can't connect to each other. Is there a way to run them somewhere online in a cloud? I will also try to run it in a virtual Ubuntu Machine, maybe some better luck there.

Do you mean to say you are not running on Linux right now?

**Comment by michielmulders** [comment] 2017-05-02 12:22
No sorry if I was not clear. I'm running on Ubuntu localhost (dualboot with Windows). 
I have set up a virtual machine running Ubuntu on my Windows, followed the documentation and on this one it is working properly.  This is the ifconfig from my Virtual Ubuntu machine on Windows:

`
docker0   Link encap:Ethernet  HWaddr 02:42:02:5e:38:5a  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:2ff:fe5e:385a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9383 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9390 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2271966 (2.2 MB)  TX bytes:1635689 (1.6 MB)

ens33     Link encap:Ethernet  HWaddr 00:0c:29:68:6d:4e  
          inet addr:192.168.189.128  Bcast:192.168.189.255  Mask:255.255.255.0
          inet6 addr: fe80::b32d:3e1f:bb19:c852/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:309450 errors:0 dropped:0 overruns:0 frame:0
          TX packets:96449 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:441217187 (441.2 MB)  TX bytes:6204101 (6.2 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1571 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1571 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:145556 (145.5 KB)  TX bytes:145556 (145.5 KB)

vethd48abb8 Link encap:Ethernet  HWaddr 5e:f2:4c:b2:c3:7a  
          inet6 addr: fe80::5cf2:4cff:feb2:c37a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8861 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9096 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2342150 (2.3 MB)  TX bytes:1595644 (1.5 MB)

vethf77162c Link encap:Ethernet  HWaddr 1e:86:32:a8:2f:db  
          inet6 addr: fe80::1c86:32ff:fea8:2fdb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:522 errors:0 dropped:0 overruns:0 frame:0
          TX packets:344 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:61178 (61.1 KB)  TX bytes:48195 (48.1 KB)
`

So I can conclude that there still is a problem with my dualboot Ubuntu machine.

**Comment by krish7919** [comment] 2017-05-02 12:32
@michielmulders : Should we close this issue as we have identified that this is a local configuration issue and not specific to running BigchainDB?
Or do you think that there is something wrong with the way we run BigchainDB that has a problem?

**Comment by michielmulders** [comment] 2017-05-02 12:33
@krish7919 You can close it, it will be a problem with my machine. I appreciate your help and time! :)

**Comment by krish7919** [comment] 2017-05-02 12:35
@michielmulders Happy hacking on BigchainDB!

**Closed by krish7919** 2017-05-02 12:35 UTC
