### ISSUE TITLE
Separate non-sensitive and sensitive configuration data

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1288] opened 2017-03-15 17:15 UTC
There is currently one configuration file that stores simple data such as the database name, but that also stores the private key of a node.

Moreover, the configuration file lives under the home directory of the user by default.

It may make sense to store the private key separately under a protected location that requires superuser privileges to access.

We may also wish to consider putting the public key of the node along with its keyring under the same protected location.

**Comment by ttmc** [comment] 2017-04-10 07:45
This issue is a duplicate of #189 and resolving it in our roadmap. I will close this one since #189 has more details.

**Closed by ttmc** 2017-04-10 07:45 UTC
Labels: proposal

**Comment by sbellem** [comment] 2017-04-10 12:07
> This issue is a duplicate of #189 and resolving it is in our roadmap. I will close this one since #189 has more details.

Makes sense with respect to the private key case.

Just as a note the issue was meant to address the problem more generally, as we may have other forms of sensitive data. One current example is the recent addition of ssl support for MongoDB connections, which may involve a password: https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/__init__.py#L32

**Comment by ttmc** [comment] 2017-04-10 14:55
Oh, good point. I think what I'll do is add a note to #189, rather than having two issues for securely managing private secrets.
