### ISSUE TITLE
Voting stops after one node is down 

### ISSUE THREAD

**Issue by gekko68** [bigchaindb/bigchaindb#413] opened 2016-06-30 12:26 UTC
I am running 0.4.2 in a distributed cluster. 3 PC's and sync etc works well. I create a transaction ( operation CREATE ) and all 3 node are voting/signing . All good. Now when I clear the collection on one PC it gets deleted in RethinkDB and Bigchain is recovering it and all entries are back.

If i now shutdown manually the bigchain process ( not the rethinkdb)  on 1 of the 3 machines the voting process in the entire cluster stops. There are still two nodes up and running. I can create see new documents in table(bigchain) but w/o block_number

Even if i start the bigchain process on THAT one node voting in the cluster is not happening , even not for transactions after all three nodes are up and running 

 below one sample document which is created but w/o voting 

{
"block": {
"node_pubkey":  "73DyzcSKVgqsiQxv1R2R5QeaNS4u3okokpDKDGG2qQJo" ,
"timestamp":  "1467287136" ,
"transactions": [
{
"id":  "67484a4653e5d8dba0c2e65fb40afbedb9aad2b79aec8a9e24f2d85b6b983aad" ,
"transaction": {
"conditions": [
{
"cid": 0 ,
"condition": {
"details": {
"bitmask": 32 ,
"public_key":  "DZdx2Mb9Savx2p6e2EB4sGdno99CjAiHh4HT7NZBacMJ" ,
"signature": null ,
"type":  "fulfillment" ,
"type_id": 4
} ,
"uri":  "cc:4:20:uqibZQ7LsgH8jeVrx1QIEOM1fsQoXUPYGF-r-Z4Hro0:96"
} ,
"new_owners": [
"DZdx2Mb9Savx2p6e2EB4sGdno99CjAiHh4HT7NZBacMJ"
]
}
] ,
"data": {
"payload": null ,
"uuid":  "d56cd537-f486-4e24-a70e-105d49224df6"
} ,
"fulfillments": [
{
"current_owners": [
"9g1BSrSiVLVv1qwVJft3Vu7rNxxWy9LB8wavLJ8sKDhE"
] ,
"fid": 0 ,
"fulfillment": "cf:4:gNtZwSCve_FAX_FO2MMsxm8N8bWZ9z6xddqaMD_T8t0gw08sDVOIyBxPLYBH1_E88WGA9fFIJa1BJRCKCpkbhZoC6225gHTwDDhN_luzGnrecpZxjhBQxcjV2DJHXCsE" ,
"input": null
}
] ,
"operation":  "CREATE" ,
"timestamp":  "1467287131"
} ,
"version": 1
}
] ,
"voters": [
"9g1BSrSiVLVv1qwVJft3Vu7rNxxWy9LB8wavLJ8sKDhE" ,
"5Bu3XgRhfhca4GbE6iTt4XJe7mZ3DuJQHhtSpya6bY9R" ,
"73DyzcSKVgqsiQxv1R2R5QeaNS4u3okokpDKDGG2qQJo"
]
} ,
"id":  "ae27b5294b422c67a815859fe74b8929fe7f5438f286aedc9f40d7ce58575442" ,
"signature":  "5bLFuR5PQkG6yj75bL8zpYadKfqpJ6nyzCc3Q2xTJk9rE2Ps7UNpywSTjUibAzj3Lf4H8iYx41nPUifbGScjhZ9w" ,
"votes": [ ]
}

**Comment by gekko68** [comment] 2016-06-30 12:52
![image](https://cloud.githubusercontent.com/assets/7279399/16488708/204c96fe-3ed2-11e6-89f1-1930209e0a32.png)
![image](https://cloud.githubusercontent.com/assets/7279399/16488718/2b1bd978-3ed2-11e6-97f1-91ed0f6d5991.png)
![image](https://cloud.githubusercontent.com/assets/7279399/16488726/337055e0-3ed2-11e6-9458-db6211f9544b.png)

After starting all node again this error message comes up .

**Comment by r-marques** [comment] 2016-06-30 13:04
Seems that it cannot find the genesis block.

Can you try again with a clean database?
1. Stop all bigchaindb instances
2. In one of the nodes do a `bigchaindb drop` and `bigchaindb init`
3. Start the bigchaindb processes in all the nodes and see if the same still happens

**Comment by gekko68** [comment] 2016-06-30 13:29
yes - that works but it is not addressing the root cause of the problem as in addition all data are gone ;-)

**Comment by r-marques** [comment] 2016-06-30 13:30
We introduce breaking changes with each release of bigchaindb. Its difficult to know in what state was your database to produce that problem

**Comment by gekko68** [comment] 2016-06-30 13:34
I created it this morning and it just had 10 records for testing purposes . I understand the code changes and no backwards compatibility. I am more concerned about the situation I have created based on 0.4.2 with and "empty" collection - only the Genesis record

**Comment by r-marques** [comment] 2016-06-30 13:59
I just need to be able to reproduce the problem. You mentioned that you deleted everything from one node and that everything was put back into the bigchain table. Maybe this was the reason that the genesis block disappeared. I will try to reproduce it

**Comment by r-marques** [comment] 2017-03-30 16:30
Closing this since it relates to a old version of BigchainDB and this issue was not raised again since then.

**Closed by r-marques** 2017-03-30 16:30 UTC
