### ISSUE TITLE
Stalled test in test_full_pipeline

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1052] opened 2017-01-17 11:28 UTC
Travis encountered this (screenshot 1), funnily enough while building a fix for another intermittent failure (#1051).

There is a use of random in this test, but wolfram alpha puts the likelyhood of a collision at 5*10^-13 (screenshot 2, note that `random()` returns 53 bit precision number) so it probably isn't that.

Failure:
![screenshot from 2017-01-17 12-15-27](https://cloud.githubusercontent.com/assets/125019/22018683/682030ea-dcb0-11e6-85f7-4910a69f2bfc.png)

Probably not because of `random()`. 100 transactions and 1<<53 possible "birthdays".
![screenshot from 2017-01-17 12-22-29](https://cloud.githubusercontent.com/assets/125019/22018684/68213bc0-dcb0-11e6-98d1-f6de0e166881.png)

**Comment by libscott** [comment] 2017-01-17 14:03
Update: Unable to reproduce after 3 hours.

**Comment by r-marques** [comment] 2017-01-17 16:07
A stalled test with the pipelines usually means that a process is blocked. My money is on some `pipe.get()`

**Comment by libscott** [comment] 2017-01-25 15:22
Yea, that's right, the question is why. I'm seeing this again (alot!) running the test suite with high concurrency on separate docker networks. 14/20 tests got blocked in test_full_pipeline.

**Comment by r-marques** [comment] 2017-01-26 08:53
Can you share the instructions to reproduce the problem?

**Comment by libscott** [comment] 2017-01-26 09:42
Sure, if you have docker-compose you should be able to just check out https://github.com/bigchaindb/bigchaindb/pull/1090 and run `scripts/floodtest.sh 20`. Don't run it in your `bigchaindb` folder because it'll create a bunch of temp files.

**Comment by r-marques** [comment] 2017-08-01 09:42
Unable to reproduce. Will close this for now.

**Closed by r-marques** 2017-08-01 09:42 UTC
