### ISSUE TITLE
Problem: BURN Operation Giving 400 BAD REQUEST

### ISSUE THREAD

**Issue by SDVII** [bigchaindb/bigchaindb#2358] opened 2018-06-22 06:32 UTC
- Device: Lenovo Yoga 720

- OS: Windows 10

- Setup: BigChainDB test network, JavaScript, Browserify

- BigChainDB Version: Latest

- Problem Details:

I am trying out CRAB as part of my job in the R&D department, and I've been relatively successful with implementing most of the functionalities. However, whenever i try to preform a BURN operation, I am getting the following error:

`Object { message: "HTTP Error: Requested page not reachable", status: "400 BAD REQUEST", requestURI: "https://test.bigchaindb.com/api/v1/transactions?mode=commit" } bundle.js:6311:7766`

My function is written like this:

```javascript
burnCrab(crabID) {
        return new Promise((resolve, reject) => {
            bdbOrm.models.crabModel
                .retrieve(crabID)
                .then(crabs => {
                    if (crabs.length) {
                        console.log(crabs[0])
                        console.log(bdbOrm.models.crabModel)
                        return crabs[0].burn(
                            {
                                keypair: this.currentIdentity,
                                asset_id: crabs[0].id
                            }
                        )
                    }
                })
                .then((burnedCrab) => {
                    resolve(burnedCrab);
                })
                .catch(err => {
                    reject(err)
                })
        })
    }
``` 
-  Attempts:
I tried to debug the issue by logging the result of each method and the tried to follow the code in the tutorial repo and found that the function is working properly till the burn operation where the error is produced.

If more details or the class itself is needed, please tell me and I'll provide whatever is necessary.
Any help would be appreciated.

**Comment by SDVII** [comment] 2018-06-22 06:54
``` JavaScript
const driver = require('bigchaindb-driver');
const bip39 = require('bip39');
var Orm = require('bigchaindb-orm').default;
require('dotenv').config()
var bdbOrm = null;

class bigChainDbAsset {
    constructor() {
        bdbOrm = new Orm(
            "https://test.bigchaindb.com/api/v1/",
            {
                app_id: "......",
                app_key: "......."
            }
        )

        bdbOrm.define("crabModel", "https://schema.org/v1/crab")
        this.currentIdentity = this.generateKeypair("test");
    }

    generateKeypair(keySeed) {
        if (typeof keySeed == "undefined" || keySeed == "") return new driver.Ed25519Keypair();
        return new driver.Ed25519Keypair(bip39.mnemonicToSeed(keySeed).slice(0, 32));
    }

    createAssetCrab() {
        return new Promise((resolve, reject) => {
            bdbOrm.models.crabModel
                .create({
                    keypair: this.currentIdentity,
                    data: {
                        breed: 'coconut crab',
                        color: 'blue'
                    }
                })
                .then(crab => {
                    console.log(crab)
                    resolve(crab)
                }).catch(err => {
                    reject(err);
                })
        })

    }

    retrieveAssetsCarb() {
        return new Promise((resolve, reject) => {
            bdbOrm.models.crabModel
                .retrieve()
                .then(assets => {
                    let crabs = assets.map(asset => asset);
                    console.log(crabs)
                    resolve(crabs);
                }).catch(err => {
                    reject(err);
                })
        })
    }

    retrieveCrab(crabID) {
        return new Promise((resolve, reject) => {
            bdbOrm.models.crabModel
                .retrieve(crabID)
                .then(assets => {
                    let crabs = assets.map(asset => asset)
                    resolve(crabs);
                }).catch(err => {
                    reject(err)
                })
        })
    }

    //burn operation not working
    burnCrab(crabID) {
        return new Promise((resolve, reject) => {
            bdbOrm.models.crabModel
                .retrieve(crabID)
                .then(crabs => {
                    if (crabs.length) {
                        console.log(crabs[0])
                        console.log(bdbOrm.models.crabModel)
                        //error
                        return crabs[0].burn(
                            {
                                keypair: this.currentIdentity,
                                asset_id: crabs[0].id
                            }
                        )
                    }
                })
                .then((burnedCrab) => {
                    resolve(burnedCrab);
                })
                .catch(err => {
                    reject(err)
                })
        })
    }

   //append not working
    updateCrab(crabID) {
        return new Promise((resolve, reject) => {
            bdbOrm.models.crabModel
                .retrieve(crabID)
                .then(crabs => {
                    if (crabs.length) {
                        console.log(crabs[0]);
                        console.log(this.currentIdentity);
                        //error
                        return crabs[0].append({
                            toPublicKey: this.currentIdentity.publicKey,
                            keypair: this.currentIdentity,
                            data: { color: 'red' }
                        })
                    }
                })
                .then((updatedCrab) => {
                    resolve(updatedCrab);
                })
                .catch(err => {
                    reject(err)
                }
            )
        })
    }
}

module.exports = { bigChainDbAsset };
```

**Comment by aadps** [comment] 2018-06-26 07:50
Hi @SDVII, I have tried to reproduce the issue, and suspect that the 400 result was produced by burning a crab that has already been burnt.

I believe the "burn" action is implemented by transferring the crab asset to a special [BURN_ADDRESS](https://github.com/bigchaindb/js-driver-orm/blob/037313e4a8052b5e054d9e8b6e0545e027b2a107/src/ormobject.js). Once that has been done, the asset is out of your hand, and no further transfer action (either "burn" or "update", since "update" is just transferring the asset to yourself) can be undertaken.

In this case, I believe 400 would be a desirable response from the web server, indicating that the illegal transaction was rejected.

**Comment by SDVII** [comment] 2018-06-28 09:18
Hi @aadps, thanks for the reply.
The asset to be burned still exist and accessible after the burn operation, so I don't think this is the result of burning an already burnt asset.

**Comment by aadps** [comment] 2018-06-28 10:14
@SDVII Can you paste the result of `console.log(crabs[0])` just before the 400 error?

**Closed** 2018-08-21 09:36 UTC
