### ISSUE TITLE
backlog maybe loss

### ISSUE THREAD

**Issue by LyLuo** [bigchaindb/bigchaindb#604] opened 2016-08-29 08:08 UTC
A federation node randomly assigns a transaction to other federation node. The received node firstly deletes the transaction from backlog , then validates transaction, creates block, write block to bigchain.
If the received node crashes after deleting the transaction from backlog, it does not write block the transaction to bigchain, the transaction would never be handle again.

**Comment by sohkai** [comment] 2016-08-29 10:05
@ttmc I believe this is a duplicate of https://github.com/bigchaindb/bigchaindb/issues/336?

**Comment by LyLuo** [comment] 2016-08-29 10:28
Could we solve the issue in bigchaindb?
after bigchiandb writes it in a block of bigchain successfully, bigchiandb deletes the transaction from backlog. This might cause there are duplicate transactions in bigchain after a bigchaindb node crashes. bigchaindb could check whether transactions exist both in backlog and bigchain after it restart from a crash.

**Comment by ttmc** [comment] 2016-08-29 11:23
@sohkai Issue #336 is slightly different.

Anyway, this issue (#604) is in the scope of what @rhsimplex is starting work on now or soon. I will reassign this issue to him.

**Comment by rhsimplex** [comment] 2016-08-30 07:24
Should be solved by proposal in #568

**Closed by rhsimplex** 2016-08-30 07:24 UTC
