### ISSUE TITLE
Invalid transactions

### ISSUE THREAD

**Issue by jindragon** [bigchaindb/bigchaindb#191] opened 2016-04-20 10:53 UTC
On two dockers. (Same physical machine, different port)
Docker1: rethinkdb --bind all
                bigchaindb start
Docker2: rethinkdb --port-offset 1 --directory /path/to/node2 --join Docker1's_host:29015
               bigchaindb start

And I executed following code.

****************************************************************************************************************************
****************************************************************************************************************************
```
import os
import logging
import argparse
import copy

import bigchaindb
import bigchaindb.config_utils
from bigchaindb import db
from bigchaindb.exceptions import DatabaseAlreadyExists
from bigchaindb.commands.utils import base_parser, start
from bigchaindb.processes import Processes
from bigchaindb import crypto
from bigchaindb import Bigchain

import time

b = Bigchain()
# CREATE A DIGITAL ASSET 
#################################################################################

# create a test user
testuser3_priv, testuser3_pub = crypto.generate_key_pair()

# define a digital asset data payload
digital_asset_payload = {'msg': 'Hello BigchainDB!'}

# a create transaction uses the operation `CREATE` and has no inputs

# all transactions need to be signed by the user creating the transaction

# write the transaction to the bigchain
# the transaction will be stored in a backlog where it will be validated,
# included in a block, and written to the bigchain
# READ THE CREATION TRANSACTION FROM THE DB 
#############################################################
# retrieve a transaction from the bigchain

f = open('test.txt', 'w')
numOfIter = 3

tx = list()
tx_signed = list()
tx_retrieved = list()
# TEST WITH PUBLIC USER 
###################################

timeSum = 0.0

for i in range(0,numOfIter):
    print("create: "+str(i))
# CREATE TEST TX 
##########################################
    tx.append( b.create_transaction(b.me, testuser3_pub, None, 'CREATE', payload=digital_asset_payload) )
    tx_signed.append( b.sign_transaction(tx[i], b.me_private) )
    b.write_transaction(tx_signed[i])
    print(tx_signed[i]['transaction']['current_owner'])
    print(tx_signed[i]['transaction']['new_owner'])
    transactions = b.get_transaction(tx_signed[i]['id'])
# TIMER START 
##############################################
    start_time = time.time()
    while transactions == None:
        transactions = b.get_transaction(tx_signed[i]['id'])
    end_time = time.time()
    if (b.is_valid_transaction(transactions) == True):
        print("VALID")
    elif (b.is_valid_transaction(transactions) == False):
        print("INVALID")
    else:
        print("DONT HAVE VALIDITY")
    print(b.validate_transaction(transactions))
    timeSum += end_time - start_time
# WRITE RESULT ON OUTPUTFILE 
###############################
print("END TEST")
f.write('Public User Create Tx Write time :\t' + str(timeSum/numOfIter) + '\n')
print('Public User Create Tx Write time :\t' + str(timeSum/numOfIter) + '\n')

for i in range(0, numOfIter):
    tx_retrieved.append( b.get_transaction(tx_signed[i]['id']) )

print("*******************************")
# TRANSFER THE DIGITAL ASSET 
############################################################################
# create a second testuser
testuser4_priv, testuser4_pub = crypto.generate_key_pair()

timeSum = 0.0

for i in range(0,numOfIter):
    print("transfer: "+str(i))
# CREATE TEST TX 
##########################################
    tx_transfer = b.create_transaction(testuser3_pub, testuser4_pub, tx_retrieved[i]['id'], 'TRANSFER')
    tx_transfer_signed = b.sign_transaction(tx_transfer, testuser3_priv)
    b.write_transaction(tx_transfer_signed)
    transactions = b.get_transaction(tx_transfer_signed['id'])
    print(tx_transfer_signed['transaction']['current_owner'])
    print(tx_transfer_signed['transaction']['new_owner'])

# TIMER START 
##############################################
    start_time = time.time()
    while transactions == None:
        transactions = b.get_transaction(tx_transfer_signed['id'])
    end_time = time.time()
    if (b.is_valid_transaction(transactions) == True):
        print("VALID")
    elif (b.is_valid_transaction(transactions) == False):
        print("INVALID")
    else:
        print("DONT HAVE VALIDITY")
    print(b.is_valid_transaction(transactions))
    timeSum += end_time - start_time

# WRITE RESULT ON OUTPUTFILE 
###############################
print("END TEST")
f.write('Public User Transfer Tx Write time :\t' + str(timeSum/numOfIter) + '\n')
print('Public User Transfer Tx Write time :\t' + str(timeSum/numOfIter) + '\n')

f.close()

# check if the transaction is already in the bigchain
tx_transfer_retrieved = b.get_transaction(tx_transfer_signed['id'])
```
*****************************************************************************************************************************
*****************************************************************************************************************************

The function 'is_valid_transaction()' 's result was valid(the return of this function was 'transactions') at CREATE and fault at TRANSFER. But the output of bigchaindb's console was invalid at CREATE('is_block_valid': Fault) and valid at TRANSFER('is_block_valid': True).

The other day formerly, I didn't check the return value of 'is_valid_transaction()' so I don't know the result of it, but the output of bigchaindb's console was opposite. Valid at CREATE and invalid at TRANSFER.

I don't know why, and I want to make every block valid.
Help me.... T.T

**Comment by diminator** [comment] 2016-04-20 12:23
Hi @jindragon,

Thanks for reporting this.
In order to reproduce, could you provide the output logs of the BigchainDB console?

**Comment by diminator** [comment] 2016-04-20 14:08
We figured this issue was reported some time ago, see #71 and resolved by #76 
Unfortunately it didn't make the release v.0.1.4

So, we created the [v0.1.5 release](https://github.com/bigchaindb/bigchaindb/releases/tag/v0.1.5)

To get your script going, please install the latest release of bigchaindb on pypi
```
pip install --upgrade bigchaindb
```

and make sure it installs v0.1.5

Again, thanks for reporting

**Closed by diminator** 2016-04-20 14:08 UTC

**Comment by jindragon** [comment] 2016-04-21 02:25
Thanks for your answer.
So, if I do 'pip install --upgrade bigchaindb',  
for example core.py will be changed exactly like this? ↓ 
https://codecov.io/github/bigchaindb/bigchaindb/bigchaindb/core.py?ref=504433fd570e0293e4fa4878e6f11cff7e6feb83

After do 'pip install --upgrade bigchaindb', I compared it with core.py in my directory,
and they are not exactly same.

But it seems that the function 'is_valid_transaction()' and 'validate_transaction()' become to work normally.

But 'is_block_valid' at bigchaindb console is still 'False' when every 'CREATE transactions'.

![console](https://cloud.githubusercontent.com/assets/16792324/14696074/163ec372-07b3-11e6-90b5-183f8d673a22.jpg)

Upper one is CREATE, and lower one is TRANSFER.

Why is it false? T.T

**Comment by diminator** [comment] 2016-04-21 08:00
Hi,

Are you using a virtualenv or a global install of bigchaindb?

Can you verify the following?

```
$ pip install bigchaindb==0.1.4
```

yields the old code, with the bug (last 3 blocks are invalid)

```
INFO:bigchaindb.config_utils:Configuration loaded from `/home/dimi/.bigchaindb`
INFO:bigchaindb.db.utils:Create:
INFO:bigchaindb.db.utils: - database `bigchain`
INFO:bigchaindb.db.utils: - tables
INFO:bigchaindb.db.utils: - indexes
INFO:bigchaindb.db.utils: - genesis block
INFO:bigchaindb.db.utils:Done, have fun!
INFO:bigchaindb.commands.bigchain:Start bigchaindb main process
INFO:bigchaindb.processes:starting bigchain mapper
INFO:bigchaindb.processes:starting backlog mapper
INFO:bigchaindb.processes:starting block
INFO:bigchaindb.processes:starting voter
INFO:bigchaindb.block:bootstraping block module...
INFO:bigchaindb.block:finished reading past transactions
INFO:bigchaindb.voter:voter waiting for new blocks
INFO:bigchaindb.block:finished bootstraping block module...
INFO:bigchaindb.block:starting block module...
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block c3cd12f3ec46dc57f377b342fb6da12c2f5004d70746a14600b2dc4416f3657a with number 1 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': 'c3cd12f3ec46dc57f377b342fb6da12c2f5004d70746a14600b2dc4416f3657a', 'previous_block': '2d3eaf58345fe97f166dfb321b61a0460dc041a254a8cb19312e150e9d68d7e3', 'invalid_reason': None, 'timestamp': '1461218094.241056'}, 'signature': '3046022100cb45bf2f37fff589bfbd6189b5c10b3b08d50e829305efef54e8e89fff998814022100a77382dc75f8829e1eb081880f26e818dff22b609917b5ae8b37fce8cf153cb3'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 5f91fbeaa8c00acd981ab030d18c1f4a3deac051c3fdf030518b6ea2a188d742 with number 2 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '5f91fbeaa8c00acd981ab030d18c1f4a3deac051c3fdf030518b6ea2a188d742', 'previous_block': 'c3cd12f3ec46dc57f377b342fb6da12c2f5004d70746a14600b2dc4416f3657a', 'invalid_reason': None, 'timestamp': '1461218099.264756'}, 'signature': '3046022100f20b5da3b8729f0316d54a133fc34148c2d6b386f2d8a83eb795baa7f6fcc1b802210082bb0c7ca97ba11d76e890c86dec752bd9912c6edc403d70ff04fd1f2072548d'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 9f73160ff2d649858cb1411f60cbed1993c2b138734f3c5a452ed4205545b28d with number 3 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '9f73160ff2d649858cb1411f60cbed1993c2b138734f3c5a452ed4205545b28d', 'previous_block': '5f91fbeaa8c00acd981ab030d18c1f4a3deac051c3fdf030518b6ea2a188d742', 'invalid_reason': None, 'timestamp': '1461218104.293335'}, 'signature': '3045022100dfc0bab4b4897b156feb5cacc4f2a98f1a8912b688f67942547a6513e947adb80220214f5579aa6e1737e29e3d7cd00f5e6b071f5a2421b6a0702d60f767dd471108'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 6bd01876b7fcff2138e0c56f50c63268bc42f344d5ab74dd6a72e628510a60ed with number 4 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '6bd01876b7fcff2138e0c56f50c63268bc42f344d5ab74dd6a72e628510a60ed', 'previous_block': '9f73160ff2d649858cb1411f60cbed1993c2b138734f3c5a452ed4205545b28d', 'invalid_reason': None, 'timestamp': '1461218109.327881'}, 'signature': '30460221009bd9147a6a5d6986ecc2436b2afdba8b1d9407b028994f28d12d471c94321a1a022100cc73507ba5ee2203745bf0819da55c70d8dffdbe23906164c1b0f98a3e683770'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 2ef268fe6ff6ce11370e7424d82e69a6d2d266d5aa609094f61aba8bba3c557a with number 5 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '2ef268fe6ff6ce11370e7424d82e69a6d2d266d5aa609094f61aba8bba3c557a', 'previous_block': '6bd01876b7fcff2138e0c56f50c63268bc42f344d5ab74dd6a72e628510a60ed', 'invalid_reason': None, 'timestamp': '1461218114.362106'}, 'signature': '304402205e77e27a0d42aeeae1c97880a47aa57a37eb6ce25718a581d232d300337b11b802200203b3d58955055e12f67c1240f67ba78fcf1b931839b62eea07e097c9fc9e98'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 549d920f2e7cdd0c644f29ec55f8d93d8fd41379aa4d0eeadc6662390ed6a581 with number 6 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '549d920f2e7cdd0c644f29ec55f8d93d8fd41379aa4d0eeadc6662390ed6a581', 'previous_block': '2ef268fe6ff6ce11370e7424d82e69a6d2d266d5aa609094f61aba8bba3c557a', 'invalid_reason': None, 'timestamp': '1461218119.394494'}, 'signature': '3044022036f574d453129859584e7787b538ec8b1b2453a7413ebd271d04a3580aa0386c02203222464c9fb2d5c2950fe0f70921856bc80e7ab82ab4d57ebba6c268bd601db9'}
```

```
$ pip install bigchaindb==0.1.5
```

yields the new code, all blocks are valid

```
INFO:bigchaindb.config_utils:Configuration loaded from `/home/dimi/.bigchaindb`
INFO:bigchaindb.db.utils:Create:
INFO:bigchaindb.db.utils: - database `bigchain`
INFO:bigchaindb.db.utils: - tables
INFO:bigchaindb.db.utils: - indexes
INFO:bigchaindb.db.utils: - genesis block
INFO:bigchaindb.db.utils:Done, have fun!
INFO:bigchaindb.commands.bigchain:Start bigchaindb main process
INFO:bigchaindb.processes:starting bigchain mapper
INFO:bigchaindb.processes:starting backlog mapper
INFO:bigchaindb.processes:starting block
INFO:bigchaindb.processes:starting voter
INFO:bigchaindb.block:bootstraping block module...
INFO:bigchaindb.block:finished reading past transactions
INFO:bigchaindb.voter:voter waiting for new blocks
INFO:bigchaindb.block:finished bootstraping block module...
INFO:bigchaindb.block:starting block module...
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block c3cd12f3ec46dc57f377b342fb6da12c2f5004d70746a14600b2dc4416f3657a with number 1 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': 'c3cd12f3ec46dc57f377b342fb6da12c2f5004d70746a14600b2dc4416f3657a', 'previous_block': '2d3eaf58345fe97f166dfb321b61a0460dc041a254a8cb19312e150e9d68d7e3', 'invalid_reason': None, 'timestamp': '1461218094.241056'}, 'signature': '3046022100cb45bf2f37fff589bfbd6189b5c10b3b08d50e829305efef54e8e89fff998814022100a77382dc75f8829e1eb081880f26e818dff22b609917b5ae8b37fce8cf153cb3'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 5f91fbeaa8c00acd981ab030d18c1f4a3deac051c3fdf030518b6ea2a188d742 with number 2 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '5f91fbeaa8c00acd981ab030d18c1f4a3deac051c3fdf030518b6ea2a188d742', 'previous_block': 'c3cd12f3ec46dc57f377b342fb6da12c2f5004d70746a14600b2dc4416f3657a', 'invalid_reason': None, 'timestamp': '1461218099.264756'}, 'signature': '3046022100f20b5da3b8729f0316d54a133fc34148c2d6b386f2d8a83eb795baa7f6fcc1b802210082bb0c7ca97ba11d76e890c86dec752bd9912c6edc403d70ff04fd1f2072548d'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 9f73160ff2d649858cb1411f60cbed1993c2b138734f3c5a452ed4205545b28d with number 3 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '9f73160ff2d649858cb1411f60cbed1993c2b138734f3c5a452ed4205545b28d', 'previous_block': '5f91fbeaa8c00acd981ab030d18c1f4a3deac051c3fdf030518b6ea2a188d742', 'invalid_reason': None, 'timestamp': '1461218104.293335'}, 'signature': '3045022100dfc0bab4b4897b156feb5cacc4f2a98f1a8912b688f67942547a6513e947adb80220214f5579aa6e1737e29e3d7cd00f5e6b071f5a2421b6a0702d60f767dd471108'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 6bd01876b7fcff2138e0c56f50c63268bc42f344d5ab74dd6a72e628510a60ed with number 4 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '6bd01876b7fcff2138e0c56f50c63268bc42f344d5ab74dd6a72e628510a60ed', 'previous_block': '9f73160ff2d649858cb1411f60cbed1993c2b138734f3c5a452ed4205545b28d', 'invalid_reason': None, 'timestamp': '1461218109.327881'}, 'signature': '30460221009bd9147a6a5d6986ecc2436b2afdba8b1d9407b028994f28d12d471c94321a1a022100cc73507ba5ee2203745bf0819da55c70d8dffdbe23906164c1b0f98a3e683770'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 2ef268fe6ff6ce11370e7424d82e69a6d2d266d5aa609094f61aba8bba3c557a with number 5 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '2ef268fe6ff6ce11370e7424d82e69a6d2d266d5aa609094f61aba8bba3c557a', 'previous_block': '6bd01876b7fcff2138e0c56f50c63268bc42f344d5ab74dd6a72e628510a60ed', 'invalid_reason': None, 'timestamp': '1461218114.362106'}, 'signature': '304402205e77e27a0d42aeeae1c97880a47aa57a37eb6ce25718a581d232d300337b11b802200203b3d58955055e12f67c1240f67ba78fcf1b931839b62eea07e097c9fc9e98'}
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:updating block 549d920f2e7cdd0c644f29ec55f8d93d8fd41379aa4d0eeadc6662390ed6a581 with number 6 and with vote {'node_pubkey': 'ufVzoYKEs36HouM7nvKBWDjyp54RBWuLCj3fZcKySncs', 'vote': {'is_block_valid': True, 'voting_for_block': '549d920f2e7cdd0c644f29ec55f8d93d8fd41379aa4d0eeadc6662390ed6a581', 'previous_block': '2ef268fe6ff6ce11370e7424d82e69a6d2d266d5aa609094f61aba8bba3c557a', 'invalid_reason': None, 'timestamp': '1461218119.394494'}, 'signature': '3044022036f574d453129859584e7787b538ec8b1b2453a7413ebd271d04a3580aa0386c02203222464c9fb2d5c2950fe0f70921856bc80e7ab82ab4d57ebba6c268bd601db9'}
```

It is quite strange that your `CREATE` tx shows up as invalid.

maybe you can refresh your DB to be sure?

```
$ bigchaindb drop
$ bigchaindb start
```

**Comment by 101vaibhav** [comment] 2016-05-26 05:47
Hello Guys... I am new in the world of bigchaindb and I would really appreciate if someone can help me with this issue as I am trying find some solution for last 7 days but could not get it right.
I have installed RethinkDb and BigchainDb on Ubuntu and I'm trying to connect bigchaindb from python. the issue is when ever i try to simply import bigchaindb, it throws following error and i cannot paas through. pls help. Error is given below:
 
Traceback (most recent call last):
  File "Main.py", line 3, in <module>
    import bigchaindb
ImportError: No module named bigchaindb

my Code:

import rethinkdb as r
import os
import bigchaindb

print("Hellow world")

**Comment by r-marques** [comment] 2016-05-26 07:59
@101vaibhav can you describe the steps you did to install bigchaindb?

**Comment by r-marques** [comment] 2016-05-26 08:06
@jindragon in the recent releases we changed our signature algorithm and from the output of your console it seems you are still using keys from the older signature algorithm.

Just to make sure can you please do:
```bash
# check the version
$ bigchaindb -v
bigchaindb 0.3.0
# recreate the configuration file with new keys
bigchaindb -y configure
# re-initialize the database
bigchaindb -y drop && bigchaindb init
$

**Comment by 101vaibhav** [comment] 2016-05-26 13:15
Hello @r-marques . Thanks for your help. I have a bigchaindb version of 0.3.0 installed on my system.
I just figured out the problem regarding the **import bigchaindb** error . The compiler was looking for a directory called bigcahindb at the same location from where I was running the my file. When I moved my code file at the same location that has the bigchaindb directory, the problem solved !!! :)

Thanks alot for your time.

**Comment by ashishbeenu** [comment] 2018-04-09 10:59
Hi All I am also facing same issue 
[2018-04-09 10:39:26] [ERROR] (bigchaindb.web.views.base) HTTP API error: 400 - POST:/api/v1/transactions - **Invalid transaction schema: '2.0' does not match** '^1\\.0$' (webapi     - pid: 7553)
I am using bigchaindb 1.3.0 version with  mongoDB version v3.6.3 under OS ubuntu1604
while creating transaction I am getting  **Invalid transaction schema: '2.0' does not match ^1\\.0$'** 
I have applied all options as suggested in this post but error still persist: Please find the below code to creating transaction:


const driver = require('bigchaindb-driver')

// BigchainDB server instance or IPDB (e.g. https://test.ipdb.io/api/v1/)
const API_PATH = 'http://localhost:9984/api/v1/'
console.log('API_PATH is::', API_PATH)
// Create a new keypair.
const alice = new driver.Ed25519Keypair()
console.log('alice is::', alice)
// Construct a transaction payload
const tx = driver.Transaction.makeCreateTransaction(
    // Define the asset to store, in this example it is the current temperature
    // (in Celsius) for the city of Berlin.
    { city: 'Berlin, DE', temperature: 22, datetime: new Date().toString() },

    // Metadata contains information about the transaction itself
    // (can be `null` if not needed)
    { what: 'My first BigchainDB transaction' },

    // A transaction needs an output
    [ driver.Transaction.makeOutput(
            driver.Transaction.makeEd25519Condition(alice.publicKey))
    ],
    alice.publicKey
)
console.log('tx is::', tx)
// Sign the transaction with private keys
const txSigned = driver.Transaction.signTransaction(tx, alice.privateKey)
console.log('txSigned is::', txSigned)
// Send the transaction off to BigchainDB
const conn = new driver.Connection(API_PATH)
console.log('conn is::', conn)
conn.postTransaction(txSigned)
    .then(() => conn.pollStatusAndFetchTransaction(txSigned.id))
    .then(retrievedTx => console.log('Transaction', retrievedTx.id, 'successfully posted.'))
Can anyone help me to resolve this issue.
