### ISSUE TITLE
GET /statuses?tx_id also needs to be able to return `INVALID`

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#1039] opened 2017-01-12 16:28 UTC
Currently when a transaction is in an `invalid` block, it returns a `404`

This is because it relies on `get_transaction(self, txid, include_status=True)`

A separate query if the above returns `(None, None)` we want to query whether that transaction is found in an `invalid` block

also affects the docs #830

**Comment by sbellem** [comment] 2017-01-18 12:00
> also affects the docs #830

addressed in 22806907a8ef46eddf0d83d22557836f6ac4e3c9

**Comment by r-marques** [comment] 2017-03-30 14:18
This is not easy to implement because we don't correctly keep track of invalid transactions. The reason for this is that we add validity to blocks and not transactions.

There are several cases that may happen here:

1. The transaction is invalid and is silently dropped at block creation time.
In this case we don't store the transaction anywhere so the transaction actually does not exist anywhere in BigchainDB. If we wanted to keep track of this we would need to store invalid transactions somewhere (another table or collection).
2. A transaction is invalid and was included in a block (which should not happen in the first place). Although tricky we could probably conclude that a particular transaction is invalid because it is in a block that was voted invalid and was never included in a valid block.
3. A transaction is valid but was included in an invalid block. In this case consensus was not actually reached yet about the transaction. During the query I may get a response that the transaction was invalid but this would be a misleading response because the transaction would go back into the backlog and eventually be included in a valid block.

If we really want this functionality the best way would be to store all invalid transactions in a separate table, collection for a limited period of time so that we don't store invalid transactions forever.

Our current behaviour is similar to how other ledges behave. An invalid transaction may be accepted by the network and will be marked as unconfirmed and once its actually processed and found invalid it will be silently discarded.

**Comment by TimDaub** [comment] 2017-06-12 15:42
Closing according to discussion in #1522.

General issue is now under #1530.

**Closed by TimDaub** 2017-06-12 15:42 UTC
Labels: topic: UX docs cmd api driver
