### ISSUE TITLE
[test/dev] Provide a way to speed up the processing of a transaction for for faster testing 

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1123] opened 2017-02-01 10:04 UTC
When working on client code, and sending requests to a BigchainDB node to post a transaction, one needs to wait, (up to 1.5 seconds), for the transaction to be ready to be part of a new transfer transaction. This makes setup code for tests very slow and inconvenient as one needs to insert sleep statements throughout the code.

There may be various approaches in tackling this issue, on both sides (server and client). This issue is concerned with a solution that is such that (strictly for development purposes), the processing of a transaction would be speed up massively, so that one can setup test cases very quickly.

**Comment by sohkai** [comment] 2017-02-10 08:46
Duplicate of #681.

**Closed by sohkai** 2017-02-10 08:46 UTC
