### ISSUE TITLE
Invalid tx: Transaction signature is invalid

### ISSUE THREAD

**Issue by lwyeluo** [bigchaindb/bigchaindb#1590] opened 2017-06-27 08:09 UTC
Hi all, I have deployed bigchaindb cluster, but when I tried to write an transaction, the bigchaindb showed that:

```
[2017-06-27 15:57:09] [WARNING] (bigchaindb.pipelines.vote) Invalid tx: Transaction signature is invalid. (Process-11 - pid: 6752)
[2017-06-27 15:57:09] [INFO] (bigchaindb.pipelines.vote) Voting 'invalid' for block e1bd9197127b669336719003fb019d9fa4f02475ee1d7f75b08adb597ff58743 (Process-14 - pid: 6760)
[2017-06-27 15:57:09] [INFO] (bigchaindb.pipelines.election) Rewriting 1 transactions from invalid block e1bd9197127b669336719003fb019d9fa4f02475ee1d7f75b08adb597ff58743 (Process-19 - pid: 6777)
```

My cluster contains 5 nodes, and the ip addresses are from 10.0.0.71 to 10.0.0.75. The version of bigchaindb is:

```
BigchainDB (0.10.2)
bigchaindb-driver (0.2.2)
```

The configuration files of bigchaindb are shown as the follows.

- 10.0.0.71:
```
{
  "log": {
    "datefmt_logfile": "%Y-%m-%d %H:%M:%S",
    "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
    "level_logfile": "info",
    "error_file": "/root/bigchaindb-errors.log",
    "granular_levels": {},
    "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
    "file": "/root/bigchaindb.log",
    "datefmt_console": "%Y-%m-%d %H:%M:%S",
    "level_console": "info"
  },
  "database": {
    "name": "bigchain",
    "replicaset": "bigchain",
    "ssl": false,
    "host": "localhost",
    "max_tries": 3,
    "login": null,
    "password": null,
    "connection_timeout": 5000,
    "port": 27017,
    "backend": "mongodb"
  },
  "backlog_reassign_delay": 120,
  "keyring": "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', 'Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv']",
  "server": {
    "loglevel": "info",
    "bind": "0.0.0.0:9984",
    "workers": null,
    "threads": null
  },
  "keypair": {
    "public": "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ",
    "private": "q7nnoEeWYN71gQs8aeDazyNYJnzBTNjTJX2RqmQL5tV"
  },
  "wsserver": {
    "host": "localhost",
    "port": 9985
  }
}
```
- 10.0.0.72:
```
root@node2:~# cat .bigchaindb | grep -A2 public
    "public": "GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv",
    "private": "Ew8ANgN9SPnPBAhc8qZVKfXxeNybN4aKqaqDVX8fL466"
  },
root@node2:~# cat .bigchaindb | grep keyring
  "keyring": "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', 'Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', '7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ']",
root@node2:~#
```

- 10.0.0.73
```
root@node3:~# cat .bigchaindb | grep -A2 public
    "public": "8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv",
    "private": "FTErjFvdjJQDqzg7gfqcVNCLgjM6e4BSXr2db4cTuBxK"
  },
root@node3:~# cat .bigchaindb | grep keyring
  "keyring": "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', 'Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv', '7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ']",
root@node3:~#
```

- 10.0.0.74
```
root@node4:~# cat .bigchaindb | grep -A2 public
    "public": "Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv",
    "private": "62GTymc8FP61d1jgo5sSptvDzSm23UbRQMx4iQ1mxrjS"
  },
root@node4:~# cat .bigchaindb | grep keyring
  "keyring": "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv', '7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ']",
root@node4:~#
```

- 10.0.0.75
```
root@node5:~# cat .bigchaindb | grep -A2 public
    "public": "GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH",
    "private": "5xYLRS7xYd5uyu6ACAsMYtx1GPLfat8tCbeZqT7nJzG2"
  },
root@node5:~# cat .bigchaindb | grep keyring
  "keyring": "['Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv', '7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ']",
root@node5:~#
```

The config of mongoDB is:

```
bigchain:PRIMARY> rs.status()
{
	"set" : "bigchain",
	"date" : ISODate("2017-06-27T08:04:43.179Z"),
	"myState" : 1,
	"term" : NumberLong(5),
	"heartbeatIntervalMillis" : NumberLong(2000),
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1498550678, 1),
			"t" : NumberLong(5)
		},
		"appliedOpTime" : {
			"ts" : Timestamp(1498550678, 1),
			"t" : NumberLong(5)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1498550678, 1),
			"t" : NumberLong(5)
		}
	},
	"members" : [
		{
			"_id" : 2,
			"name" : "10.0.0.72:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 3017,
			"optime" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDate" : ISODate("2017-06-27T08:04:38Z"),
			"electionTime" : Timestamp(1498547666, 1),
			"electionDate" : ISODate("2017-06-27T07:14:26Z"),
			"configVersion" : 18,
			"self" : true
		},
		{
			"_id" : 3,
			"name" : "10.0.0.71:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 2824,
			"optime" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDate" : ISODate("2017-06-27T08:04:38Z"),
			"optimeDurableDate" : ISODate("2017-06-27T08:04:38Z"),
			"lastHeartbeat" : ISODate("2017-06-27T08:04:42.628Z"),
			"lastHeartbeatRecv" : ISODate("2017-06-27T08:04:42.628Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "10.0.0.75:27017",
			"configVersion" : 18
		},
		{
			"_id" : 4,
			"name" : "10.0.0.73:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 2824,
			"optime" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDate" : ISODate("2017-06-27T08:04:38Z"),
			"optimeDurableDate" : ISODate("2017-06-27T08:04:38Z"),
			"lastHeartbeat" : ISODate("2017-06-27T08:04:42.628Z"),
			"lastHeartbeatRecv" : ISODate("2017-06-27T08:04:42.626Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "10.0.0.75:27017",
			"configVersion" : 18
		},
		{
			"_id" : 5,
			"name" : "10.0.0.74:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 2824,
			"optime" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDate" : ISODate("2017-06-27T08:04:38Z"),
			"optimeDurableDate" : ISODate("2017-06-27T08:04:38Z"),
			"lastHeartbeat" : ISODate("2017-06-27T08:04:42.629Z"),
			"lastHeartbeatRecv" : ISODate("2017-06-27T08:04:42.728Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "10.0.0.72:27017",
			"configVersion" : 18
		},
		{
			"_id" : 6,
			"name" : "10.0.0.75:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 2824,
			"optime" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1498550678, 1),
				"t" : NumberLong(5)
			},
			"optimeDate" : ISODate("2017-06-27T08:04:38Z"),
			"optimeDurableDate" : ISODate("2017-06-27T08:04:38Z"),
			"lastHeartbeat" : ISODate("2017-06-27T08:04:42.628Z"),
			"lastHeartbeatRecv" : ISODate("2017-06-27T08:04:42.630Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "10.0.0.72:27017",
			"configVersion" : 18
		}
	],
	"ok" : 1
}
```

The code to write data is（I run it in 10.0.0.71）:

```
import bigchaindb_driver
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
from time import sleep
import json
from sys import exit
import sys

class BigChainAPI(object):

    def __init__(self, host, port=9984, conf='/root/.bigchaindb', timeout=60):
        '''
        :param host: cluster host of bigchaindb
        :param port: port of bigchaindb
        :param conf: the configuration file of bigchaindb
        :param timeout: waiting vote for `timeout` seconds
        :return:
        '''
        self.host = host
        self.port = int(port)
        self.bdb = BigchainDB("http://%s:%d" % (self.host, self.port))

        self.conf = conf
        self.timeout = int(timeout)

        self.loadUserKey()

    def loadUserKey(self):
        '''
        load user key from configuration files, as the valid keypairs are
         designated in our deployment
        :return:
        '''
        configuration = json.load(open(self.conf, "r"))
        self.user = configuration['keypair']

    def writeTransaction(self, data, metadata=None):
        '''
        write data into bigchaindb
        :param data: the data to write. it should be a dict
        :param metadata: the metadata to write. it should be a dict
        :return: the transaction is
        '''
        _asset = {
            'data': data
        }

        prepared_creation_tx = self.bdb.transactions.prepare(
            operation='CREATE',
            signers=self.user['public'],
            asset=_asset,
            metadata=metadata
        )

        fulfilled_creation_tx = self.bdb.transactions.fulfill(
            prepared_creation_tx,
            private_keys=self.user['private']
        )

        sent_creation_tx = self.bdb.transactions.send(fulfilled_creation_tx)

        txid = fulfilled_creation_tx['id']
        print("txid is ", txid)
        trials = 0
        while trials < self.timeout:
            try:
                if self.bdb.transactions.status(txid).get('status') == 'valid':
                    print('Tx valid in:', trials, 'secs')
                    break
                elif self.bdb.transactions.status(txid).get('status') == 'invalid':
                    print('Tx invalid in:', trials, 'secs')
                    print(self.bdb.transactions.status(txid))
                    break
                else:
                    trials += 1
                    print("trials " + str(trials))
                    sleep(1)
            except bigchaindb_driver.exceptions.NotFoundError:
                trials += 1
                sleep(1)

        if trials == self.timeout:
            print('Tx is still being processed... Bye!')
            return False

        return txid

    def queryTransaction(self, txid):
        '''
        retrieve a transaction
        :param txid: the txid of the transaction to query
        :return: the data of the retrieved transaction
        '''
        data = self.bdb.transactions.retrieve(txid)

        return data['asset']['data']

def test():
    bigchainAPI = BigChainAPI(host='10.0.0.71', port=9984, timeout=300)

    # write an transaction
    data = {
        'author': 'Wu Luo'
    }
    txid = bigchainAPI.writeTransaction(data)
    if txid == False:
        print(">>> waiting for vote")
        return False

test()
```

I can not figure out why it shows "Invalid tx: Transaction signature is invalid. ". Is there something wrong for my cluster? Please help me. Thanks.

**Comment by TimDaub** [comment] 2017-06-27 08:20
Hi @lwyeluo, would you mind sending us a jsonized version of your transaction either here on Github or via email to tim@bigchaindb.com? Thanks :)

**Comment by lwyeluo** [comment] 2017-06-27 08:39
Thanks for you reply.
When I start bigchaindb, data in MongoDB are:

```
bigchain:PRIMARY> db.bigchain.find()
{ "_id" : ObjectId("595217531645462eb7b939b2"), "block" : { "node_pubkey" : "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ", "transactions" : [ { "asset" : { "data" : null },"inputs" : [ { "fulfills" : null, "fulfillment" : "cf:4:WrZpzR0UXhQjIDgtjtKUlTRlYW4L13L2WIA3bUQB_LaMPRRev0IDPdNEEbJTpn6I_61RYMkIUcZ_WIR-FA1woI62G4-KpecZVrKP9HFCCQddwTu8_Qy3R36Mud5_JgQG", "owners_before" : [ "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ] } ],"outputs" : [ { "amount" : 1, "public_keys" : [ "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ], "condition" : { "details" : { "public_key" : "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ", "signature" : null, "type" : "fulfillment", "bitmask" : 32, "type_id": 4 }, "uri" : "cc:4:20:WrZpzR0UXhQjIDgtjtKUlTRlYW4L13L2WIA3bUQB_LY:96" } } ], "operation" : "GENESIS", "metadata" : { "message" : "Hello World from the BigchainDB" }, "id" : "190d91ca3130aeb6522ed1b2c75e8abd40c8c5c5c1f44d634ac3793ff9d16c03", "version" : "0.10" } ], "timestamp" : "1498552147", "voters" : [ "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', 'Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv']", "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ] }, "signature" : "4WmketcoQ5XF8XK7ok2a6Z4AFWECHMbkzo6cnAbXTcqPyPW6HUjXZbCEY9EtHTPKsY23WAK9MHPWXX9f6htwmN7K", "id" : "a34d965bd81a502cdbcd516a5a514d39be76eda2da25026aadfe3041f8898621" }
bigchain:PRIMARY> db.votes.find()
bigchain:PRIMARY> db.backlog.find()
bigchain:PRIMARY>
```

After I run my script to write a transaction and an error has occured, the data in MongoDb are:

```
bigchain:PRIMARY> db.bigchain.find()
{ "_id" : ObjectId("595217531645462eb7b939b2"), "block" : { "node_pubkey" : "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ", "transactions" : [ { "asset" : { "data" : null },"inputs" : [ { "fulfills" : null, "fulfillment" : "cf:4:WrZpzR0UXhQjIDgtjtKUlTRlYW4L13L2WIA3bUQB_LaMPRRev0IDPdNEEbJTpn6I_61RYMkIUcZ_WIR-FA1woI62G4-KpecZVrKP9HFCCQddwTu8_Qy3R36Mud5_JgQG", "owners_before" : [ "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ] } ],"outputs" : [ { "amount" : 1, "public_keys" : [ "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ], "condition" : { "details" : { "public_key" : "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ", "signature" : null, "type" : "fulfillment", "bitmask" : 32, "type_id": 4 }, "uri" : "cc:4:20:WrZpzR0UXhQjIDgtjtKUlTRlYW4L13L2WIA3bUQB_LY:96" } } ], "operation" : "GENESIS", "metadata" : { "message" : "Hello World from the BigchainDB" }, "id" : "190d91ca3130aeb6522ed1b2c75e8abd40c8c5c5c1f44d634ac3793ff9d16c03", "version" : "0.10" } ], "timestamp" : "1498552147", "voters" : [ "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', 'Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv']", "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ] }, "signature" : "4WmketcoQ5XF8XK7ok2a6Z4AFWECHMbkzo6cnAbXTcqPyPW6HUjXZbCEY9EtHTPKsY23WAK9MHPWXX9f6htwmN7K", "id" : "a34d965bd81a502cdbcd516a5a514d39be76eda2da25026aadfe3041f8898621" }
{ "_id" : ObjectId("5952187cb2e21d24606da6c2"), "id" : "34917a54e38fb7402c7fabcf4b126e12a8ae9cbf5264d53ee3a46cbf8ce2d777", "signature" : "44x75gihGMyLxtjMG6y5pdhyLhpKqkx9jdeGLuW8ZarQaqfS2fStDTyijhi8AgPBcqKiypspfA1BRTLyMRwqTJ8z", "block" : { "transactions" : [ { "asset" : { "data" : { "author" : "Wu Luo" } }, "version" : "0.10", "inputs" : [ { "fulfillment" : "cf:4:WrZpzR0UXhQjIDgtjtKUlTRlYW4L13L2WIA3bUQB_LbRYP9ebWbMfEWccJ2x-sp7ZAhT9QI5aQvCGCF_aexsPhRUHxu9vsA9egf9a3y3RLxYFVkv_a2GsKyDNpDen2oI", "owners_before" : [ "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ], "fulfills" : null } ], "id" : "7f5fb0303fa117423ec59c3939282a4035370a2d6cbd92f5168b189bc03c213d", "operation" : "CREATE", "outputs" : [ { "public_keys" : [ "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ], "condition" : { "details" : { "type_id" : 4, "public_key" : "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ", "signature" : null, "bitmask" : 32, "type" : "fulfillment" }, "uri" : "cc:4:20:WrZpzR0UXhQjIDgtjtKUlTRlYW4L13L2WIA3bUQB_LY:96" }, "amount" : 1 } ], "metadata" : null } ], "node_pubkey" : "GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH", "timestamp" :"1498552444", "voters" : [ "['Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv', '7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ']", "GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH" ] } }
```

```
bigchain:PRIMARY> db.votes.find()
{ "_id" : ObjectId("5952187c1645462f853b2d29"), "signature" : "4G47txZPbU8fBk3244nmHeL9d9RKfJnPN5yLFxK92M8qFhuCA9go5YqcXarYjjVnUXRMFfjdh3bBDiAmhTfhSFVE", "node_pubkey" : "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ", "vote" : { "invalid_reason" : null, "is_block_valid" : false, "previous_block" : "a34d965bd81a502cdbcd516a5a514d39be76eda2da25026aadfe3041f8898621", "voting_for_block" : "34917a54e38fb7402c7fabcf4b126e12a8ae9cbf5264d53ee3a46cbf8ce2d777", "timestamp" : "1498552444" } }
{ "_id" : ObjectId("5952187cb2e21d248b6da6c6"), "signature" : "36SXZBrRRAkPgnSn77eNy1b7LrcCnhTmN6Vxk9p28w72z8gMKzsYtLLdMZe4dogkHYK8PVLYksVAp1mz2p4bZv6y", "node_pubkey" : "GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH", "vote" : { "previous_block" : "a34d965bd81a502cdbcd516a5a514d39be76eda2da25026aadfe3041f8898621", "invalid_reason" : null, "voting_for_block" : "34917a54e38fb7402c7fabcf4b126e12a8ae9cbf5264d53ee3a46cbf8ce2d777", "timestamp" : "1498552444", "is_block_valid" : true } }
```

**Comment by TimDaub** [comment] 2017-06-27 13:34
Hi @lwyeluo, thanks for reporting and special thanks for providing us with all required information.
@r-marques and I spent some time looking into the problem.

As far as we can judge, the transaction you script is generating is correct.
The block, the transaction was included in (a34d965bd81a502cdbcd516a5a514d39be76eda2da25026aadfe3041f8898621) however includes a weirdly formatted `voters` list:

```json
"voters" : [ "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', 'Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv']", "7772APkwHENC8j3tDaUK2WJYPF3AMrTkVgR7sW1y3bkZ" ]
```

BigchainDB expects this value to be a list of public keys, not a list of one string containing the list of public keys :laughing:. We checked your configurations and found that you configured the `keyring` in the same format, which likely caused the nodes to not be able to extract any useful information out of `block.voters`.

To fix your problem, in your configuration try changing:

```json
// your configuration
"keyring": "['GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH', 'Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv', '8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv', 'GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv']",

// to

"keyring": ["GH3uAPwi1MzXsxy4PJdj4p5m55nXuLAakNtpFNJw7cqH", "Eok1FnDbKpak9t6SpJVpFsMqkvNiVGsys6BP8UbSiCTv", "8bXEbEJVCDNhptYyAJ5WWHCngiie6VuwTKF5NmZ4Fazv", "GRTkTmFuYETDaXAftSZW1SdCMMwaYs6p6yhAn5C4QBZv"],

// and respectively for all nodes in the cluster
```

Please let us know if this resolves your issue.

On the error message itself, @r-marques will take a look why BigchainDB claimed to have executed an invalid transaction:

```
[2017-06-27 15:57:09] [WARNING] (bigchaindb.pipelines.vote) Invalid tx: Transaction signature is invalid. (Process-11 - pid: 6752)
```

Once this is clarified/fixed, we'll close this issue.

**Comment by lwyeluo** [comment] 2017-06-27 13:58
Hi, @TimDaub and @r-marques . Great thanks for your help. 

I have written some codes to automatically generate the `keyring` into the configuration files. It's my mistake to add an additional `str()` when generating the value of key `keyring`. Once I correct it, the transaction is successfully written into bigchainDB. Great thanks~

**Comment by TimDaub** [comment] 2017-06-27 14:06
> Once I correct it, the transaction is successfully written into bigchainDB. Great thanks~

Great :tada:. Glad we could help you.

I'll reopen this issue to have us improve/clarify the error message.
@r-marques was assigned.

**Comment by r-marques** [comment] 2017-06-27 14:46
I checked the code and we indeed print out a misleading message.
The problem is that in the voting pipeline when the block is invalid for some reason (in this case because the voter was not a federation member) we insert a dummy invalid transaction into the pipeline to force the block to be voted invalid. We do this because we cannot interrupt the pipeline https://github.com/bigchaindb/bigchaindb/blob/v1.0.0rc1/bigchaindb/pipelines/vote.py#L64.

Two things need to happen.
- Print and message with the reason why the block is invalid https://github.com/bigchaindb/bigchaindb/blob/v1.0.0rc1/bigchaindb/pipelines/vote.py#L63
- Don't print a message if we are using the dummy transaction and possibly skip the validation https://github.com/bigchaindb/bigchaindb/blob/v1.0.0rc1/bigchaindb/pipelines/vote.py#L113

Here is some code to reproduce the problem:

```python
from bigchaindb import Bigchain
from bigchaindb.models import Transaction

b = Bigchain()
tx = Transaction.create([b.me], [([b.me], 1)]).sign([b.me_private])
block = b.create_block([tx])

# this invalidates the block
block.voters = ['aaa']
b.write_block(block)
```

**Comment by r-marques** [comment] 2017-06-27 14:52
I flagged this as a bug since it made it difficult to debug what the actual problem was.

**Comment by sbellem** [comment] 2017-07-04 12:46
fyi: on it, but paused for now.

**Comment by ttmc** [comment] 2018-05-28 18:26
The problem was with the voting pipeline, which is no longer used, and soon all the voting-pipeline code will be gone. (Voting is now handled by Tendermint and is not the concern of BigchainDB Server.)

I'm closing this issue.

**Closed by ttmc** 2018-05-28 18:26 UTC
Labels: BUG
