### ISSUE TITLE
bigchaindb start failed

### ISSUE THREAD

**Issue by kedarrane** [bigchaindb/bigchaindb#2640] opened 2019-03-24 07:26 UTC
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/utils.py", line 48, in run
    super().run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/web/websocket_server.py", line 185, in start
    port=config['wsserver']['port'])
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 415, in run_app
    reuse_port=reuse_port))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 341, in _run_app
    await site.start()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_runner.py", line 102, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1019, in create_server
    infos = yield from tasks.gather(*fs, loop=self)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 968, in _create_server_getaddrinfo
    flags=flags, loop=self)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by ttmc** [comment] 2019-03-25 08:40
I'm closing this issue because it fails to give enough information for anyone to reproduce the problem. What operating system was used? What version of BigchainDB? How many nodes? What was the overall configuration? etc.

**Closed by ttmc** 2019-03-25 08:40 UTC
