### ISSUE TITLE
/api/v1/outputs/ endpoint not working

### ISSUE THREAD

**Issue by lkong** [bigchaindb/bigchaindb#2370] opened 2018-06-29 23:35 UTC
OS- Debian 9
BigchainDB - 2.0.0b1
tendermint - 0.21.0-46369a1a
mongodb- 3.6.5
Deployed running directly in a VM.

Symptom:
/api/v1/assets/ endpoint is functioning normal
/api/v1/transactions endpoint is functioning normal
/api/v1/outputs returns 500 error.

Logs from bigchaidb:
```
[2018-06-29 23:19:22] [ERROR] (flask.app) Exception on /api/v1/outputs [GET] (bigchaindb_webapi - pid: 2290)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/connection.py", line 61, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/utils.py", line 166, in run
    last = last(*item[0], **item[1])
  File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 2397, in aggregate
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 2304, in _aggregate
    client=self.__database.client)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: $projection requires at least one output field
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/web/views/outputs.py", line 24, in get
    args['spent'])
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/core.py", line 325, in get_outputs_filtered
    outputs = self.fastquery.get_outputs_by_public_key(owner)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/tendermint/fastquery.py", line 17, in get_outputs_by_public_key
    txs = list(query.get_owned_ids(self.connection, public_key))
  File "/usr/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/query.py", line 183, in get_owned_ids
    {'$project': {'_id': False}}
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/connection.py", line 72, in run
    raise OperationError from exc
bigchaindb.backend.exceptions.OperationError
```

**Comment by codegeschrei** [comment] 2018-07-02 07:50
Hey @lkong 
Can you provide some more information? Did you run a script or anything?
I tried to reproduce the issue but the endpoint works for me.

**Comment by lkong** [comment] 2018-07-02 16:01
For example, I have this object (https://pastebin.com/CSCKFAak) in my mongodb.
Hitting http://bigchaindb:9984/api/v1/transactions/37446285b517880c95eb7f8ec8f07cacf6057808b7f2141b4f0f2414198a69a3 will return the object.
However http://bigchaindb:9984/api/v1/outputs?public_key=Gfk3UTvRevMHitdcnnukkEbm9eHTijTRvQcTfXYnrtP&spent=false
Will result in HTTP 500 or no response.

**Comment by codegeschrei** [comment] 2018-07-02 16:20
In your error it says `pymongo.errors.OperationFailure: $projection requires at least one output field`
Can you provide me with your `create` transaction too and maybe check that the `output` field was set?

**Comment by lkong** [comment] 2018-07-02 18:52
{'asset': {'data': {'__Salt': 'YUl98qsl7XExKtdd', '__Type': 'SphereApiLog', 'origin': 'tendy', 'scope': 'mctendies', 'timestamp': '2018-07-02T00:00:00'}}, 'id': '07d00e7df43081f21921b72ba906c8a4adf49b9c567a0995e3ff73309bf45b4f', 'inputs': [{'fulfillment': 'pGSAIEqkSXQxJSjHhLIO6WGCa9oi7mTvTB1dmXSx_skMFhKPgUAHPQnQiQGYRq9o0Ic1g1mpjydP50eVks1i5g-C_4PyTLWWiE73GSz2skiO8mETYTiC-xPqW6Huzcr-Jnr-vtMN', 'fulfills': None, 'owners_before': ['62NU23WL1MMZZjp9ms1Bxh7ixHHX8UrfgTu6DXZEwUXx']}], 'metadata': None, 'operation': 'CREATE', 'outputs': [{'amount': '1', 'condition': {'details': {'public_key': '62NU23WL1MMZZjp9ms1Bxh7ixHHX8UrfgTu6DXZEwUXx', 'type': 'ed25519-sha-256'}, 'uri': 'ni:///sha-256;e3gW7R9HaSwly0bkrdqvoWqUssLm6PlV6a4kQK5_H8s?fpt=ed25519-sha-256&cost=131072'}, 'public_keys': ['62NU23WL1MMZZjp9ms1Bxh7ixHHX8UrfgTu6DXZEwUXx']}], 'version': '2.0'}

This is one of our typical creation_tx.
It gets through successuflly, but we can not query outputs for the given public key.

**Comment by codegeschrei** [comment] 2018-07-03 08:31
When you post the transactions, which `mode` do you use? If you use `async` maybe the transaction was not valid?
I tried again to reproduce it but without any success. Maybe you can provide a small script on how to send a create and transfer transaction?

**Comment by lkong** [comment] 2018-07-03 20:20
https://gist.github.com/lkong/fe4efab7097914952fb9ae4cc51992b7

Here's the gist for it.

**Comment by lkong** [comment] 2018-07-06 21:58
The problem disappears if I deploy the same configuration inside of docker environment.

**Comment by muawiakh** [comment] 2018-07-16 16:59
Can you share the steps to reproduce? How you are deploying BigchainDB on your host machine?

I also notice there is a slight discrepancy in the versions , BigchainDB `2.0.0b1` is supported with Tendermint `0.19.x` but you are using it with `0.21.0-46369a1a`.

I deployed the following:
```
OS: PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
BigchainDB: master >= (2.0.0b2)
Tendermint: 0.22.4-c64a3c74
```

and all the endpoints are working as expected.

**Comment by ttmc** [comment] 2018-09-14 15:15
We were unable to reproduce this problem so I'm closing it.

**Closed by ttmc** 2018-09-14 15:15 UTC
