### ISSUE TITLE
DoubleSpend bug ?

### ISSUE THREAD

**Issue by yuyuxp** [bigchaindb/bigchaindb#2527] opened 2018-09-10 08:25 UTC
I found a bug , wrong DoubleSpend, I Can't tansfer the asset

My bigchaindb server version is bigchaindb 2.0.0a6 ,and it run on my ubuntu server 18.04(x64)

I use python driver ,and the code is that:
```python
def transfer_asset2(asset_tx_idx_list, recipients, owner_private_keys,metadata):
    transfer_input_list = []
    for asset_tx_idx in asset_tx_idx_list:
        print(asset_tx_idx)
        tx_id = asset_tx_idx['transaction_id']
        output_index =asset_tx_idx['output_index']
        tx = bdb.transactions.retrieve(tx_id)
        transfer_input = {
            'fulfillment': tx['outputs'][output_index]['condition']['details'],
            'fulfills': {
                'output_index': output_index,
                'transaction_id': tx_id,
            },
            'owners_before': tx['outputs'][output_index]['public_keys'],
        }
        transfer_input_list.append(transfer_input)
        asset_id={}
        if tx['operation']=='CREATE':
            asset_id['id']=tx['id']
        else:
            asset_id=tx['asset']
    #print(transfer_input_list,transfer_asset_list)
    prepared_transfer_tx = bdb.transactions.prepare(
        operation='TRANSFER',
        asset=asset_id,
        inputs=transfer_input_list,
        recipients=recipients,
        metadata=metadata
    )
    fulfilled_transfer_tx = bdb.transactions.fulfill(
        prepared_transfer_tx, private_keys=owner_private_keys)
    sent_transfer_tx = bdb.transactions.send_commit(fulfilled_transfer_tx)
    if sent_transfer_tx == fulfilled_transfer_tx:
        return True
    else:
        return False

### #TEST
r= bdb.outputs.get('AUENr3BCgeDSe5podee1PH4aV1AdMEAeJ8P5bZgiQyiM',spent=False)
for i in r:
    print(i)
r=bdb.transactions.retrieve('203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35')
print(r)
dic = {'transaction_id': '203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35', 'output_index': 0}
list1=[]
list1.append(dic)
r=transfer_asset2(list1,[(['7RYDZtnVp9SGuzv85ECiAEDRLUgVxQULCcgwYNaowdMU'], 2)],['AYF6qz3paXf1aiPot4VAPQGY3NiQ2WQwdUnktucJNiQF'],metadata)
print(r)
```

and result is that:
```
{'transaction_id': 'bb15a81f6952eb9df93089f544df1490ef94ae9313f5481f661ae245271a8a84', 'output_index': 0}
{'transaction_id': '7c520a7f9eb931c29d8a826a91f48721890de6707d1eaafcfb5b1206a1c0c9c0', 'output_index': 0}
{'transaction_id': '1a75b2bc327438d3f9c4cc694f13c4f6f88ffc424a2a620a403798c1bbcff604', 'output_index': 0}
{'transaction_id': '1b1bbda1863fda2214025b28d659d81b430a084dbadccb5197a3bad297b932d9', 'output_index': 0}
{'transaction_id': 'dd23404fdcd125ed8552f3cbeab19adff13919e5bff48060db3aa1cec09469ea', 'output_index': 0}
{'transaction_id': '2a99e47e0d59777c33b7720773cf20a411853d4b7f68db67456a306747eebe04', 'output_index': 0}
### {'transaction_id': '203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35', 'output_index': 0}
{'transaction_id': '254879b445c5080e1dbd1eea5c1a96de7610037d514b8e56a96088f6fd2c96ec', 'output_index': 0}
{'transaction_id': '4334e8d82422124071b2defcc7ece08df8dd6b9579c6e2ed85056394633d6224', 'output_index': 0}
{'transaction_id': 'd121f43c9e360414f3c6728d968fd69fd9d5150c5cd2c9653fcb7f92da8a5dd5', 'output_index': 0}
{'transaction_id': '7c916bc2a5ab33d2a709942f35b177c852a41b0d8d765d4322773d63632866b0', 'output_index': 0}
{'inputs': [{'owners_before': ['7RYDZtnVp9SGuzv85ECiAEDRLUgVxQULCcgwYNaowdMU'], 'fulfills': {'transaction_id': '20d747c2ec79df25666a91ced681151f481be3b799cf6ee2d07dc57ef62dd953', 'output_index': 1}, 'fulfillment': 'pGSAIF9vW5ed50NBPonZ4zNO039vNlt5V0AnP772CSkWgW1jgUA0s_toF2AbOJx5MRGpceoZNWo7wKC1jK4Gw11HID4rqWdPefe3pPZW_vhi998YPx0KkiQjxQEodSxFwywvXcwD'}], ### 'outputs': [{'public_keys': ['AUENr3BCgeDSe5podee1PH4aV1AdMEAeJ8P5bZgiQyiM'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'AUENr3BCgeDSe5podee1PH4aV1AdMEAeJ8P5bZgiQyiM'}, 'uri': 'ni:///sha-256;W0Q_u1Pxr_wrWgmUfA6taa9MsvjGxqxRbMikuXAS6tY?fpt=ed25519-sha-256&cost=131072'}, 'amount': '2'}, {'public_keys': ['Ea31fn42KJSLcUbtb2YrWxyqove5r2eETe9B1RZ82MGa'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'Ea31fn42KJSLcUbtb2YrWxyqove5r2eETe9B1RZ82MGa'}, 'uri': 'ni:///sha-256;z58cQPGh3APGjmqFeVsE8ybb8FD_WdoyXyBhPaDSCks?fpt=ed25519-sha-256&cost=131072'}, 'amount': '3'}], 'operation': 'TRANSFER', 'metadat...
{'transaction_id': '203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35', 'output_index': 0}

bigchaindb_driver.exceptions.BadRequest: (400, '{"message":"Invalid transaction (DoubleSpend): input  `203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35` was already spent","status":400}\n', **### {'message': 'Invalid transaction (DoubleSpend)**: input `203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35` was already spent', 'status': 400})
```

and I use http API to query the outputs, http://192.168.10.13:9984/api/v1/outputs?public_key=AUENr3BCgeDSe5podee1PH4aV1AdMEAeJ8P5bZgiQyiM&spent=false
It's same as use python driver 

Is it a bug ?

**Comment by codegeschrei** [comment] 2018-09-11 11:53
Did you try to spent an output twice? If not can you provide us with more information? For example a complete example with the transactions you use?

@kansi what other information would be helpful?

**Comment by kansi** [comment] 2018-09-11 11:56
@yuyuxp It is unclear which outputs belongs to which print statement. I would urge you to properly format the information so that we can appropriately reproduce the scenario. Nevertheless, I tried to generate a `create` transaction and `transfer` the outputs to other users and there doesn't seem to be any issues there. Maybe if you can describe your scenario more clearly we might be able to help better.

**Comment by yuyuxp** [comment] 2018-09-12 02:17
@kansi Hi,I send a mail to you and leave a message.
@codegeschrei can you leave a email address for me ? I can show you my test server enviroment and my email is 20114930@qq.com

**Comment by kansi** [comment] 2018-09-12 07:30
@yuyuxp Can you please post your message here so that the information is available to everyone

**Comment by yuyuxp** [comment] 2018-09-12 07:40
OK.everyone can test it.
my test eviroment:
bdb_root_url = 'http://stlab.meibu.net:9984'
bdb = BigchainDB(bdb_root_url)

the asset_id is '7cf0b4d18d1a573169060add6cb785ca9ed697934981132584160bc7d678ddfb'
and the output I want to transfer is transaction_id:203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35 output_index:0
but I can't transfer it ,because of doublespend error

for test keypares:
public_key:AUENr3BCgeDSe5podee1PH4aV1AdMEAeJ8P5bZgiQyiM	
private_key:AYF6qz3paXf1aiPot4VAPQGY3NiQ2WQwdUnktucJNiQF

public_key:Ea31fn42KJSLcUbtb2YrWxyqove5r2eETe9B1RZ82MGa	
private_key:GL9oXuR1Ee4nKgwK9KLJWXMVv5zyuSSzXjjTv1f1QWc8

public_key:7RYDZtnVp9SGuzv85ECiAEDRLUgVxQULCcgwYNaowdMU	
private_key:2C722ydMrgEUDzuEnzSWRhzCwh5PygeZp12UQm896zSV

**Comment by yuyuxp** [comment] 2018-09-12 08:37
@kansi 
My test enviroment is 4 nodes, all is running
BigchainDB log :
[2018-09-12 16:11:09] [ERROR] (bigchaindb.web.views.base) HTTP API error: 400 - POST:/api/v1/transactions - Invalid transaction (DoubleSpend): input `203019472d1d
206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35` was already spent (webapi     - pid: 1636)

Tendermint log:

[tendermint.log](https://github.com/bigchaindb/bigchaindb/files/2374218/tendermint.log)

**Comment by ttmc** [comment] 2018-09-12 08:40
> My bigchaindb server version is bigchaindb 2.0.0a6

Version 2.0.0a6 is an old version of BigchainDB Server, released in May. We fixed some bugs since then. Please use the latest version of BigchainDB Server, which, as I write this, is 2.0.0b5.

**Comment by kansi** [comment] 2018-09-12 08:44
I agree with @ttmc, we fixed an issue sometime ago regarding valid transactions being detected as double spends #2389 . It would best if you migrate to `2.0.0b5`

**Comment by yuyuxp** [comment] 2018-09-12 08:58
@kansi @ttmc  OK.I'll try to migrate to new version

**Comment by yuyuxp** [comment] 2018-09-16 02:54
@kansi @ttmc  @codegeschrei  
thanks for your help.
The problem is resolved  when I upgrade the Bigchaindb Server version to 2.0.0b5, and the transaction's infomation is that
{
    "inputs": 
    [
        {
            "owners_before": 
            [
                "AUENr3BCgeDSe5podee1PH4aV1AdMEAeJ8P5bZgiQyiM"
            ],
             "fulfills": 
            {
                "transaction_id": "203019472d1d206574d3a0b0fe038f3f9eae3aa9953b434ba812a5743fca1e35",
                 "output_index": 0
            },
             "fulfillment": "pGSAIIyy_Tx8F7xtMlYYm5CwM0egxtOBBelq8FXVwuDXhQbGgUBAvkIwngdK9HvQUurTrEp5KaEXaGW2SqHz0Y1VT9GlIulKH8IKAcidDjB14XyBN6j5vT3lCi9BK4RVflnd5KYI"
        }
    ],
     "outputs": 
    [
        {
            "public_keys": 
            [
                "7RYDZtnVp9SGuzv85ECiAEDRLUgVxQULCcgwYNaowdMU"
            ],
             "condition": 
            {
                "details": 
                {
                    "type": "ed25519-sha-256",
                     "public_key": "7RYDZtnVp9SGuzv85ECiAEDRLUgVxQULCcgwYNaowdMU"
                },
                 "uri": "ni:///sha-256;gd5B3nFHssNkY7qgu5lvPsw2ulaJcocYtFZ43LmtIrc?fpt=ed25519-sha-256&cost=131072"
            },
             "amount": "2"
        }
    ],
     "operation": "TRANSFER",
     "metadata": 
    {
        "transfer_time": "2018-09-14 09:56:46 017142"
    },
     "asset": 
    {
        "id": "7cf0b4d18d1a573169060add6cb785ca9ed697934981132584160bc7d678ddfb"
    },
     "version": "2.0",
     "id": "bc67580af851554638104e4b20b671c781d0c10becb62cb4b5b20584b2c37963"
}

**Comment by ttmc** [comment] 2018-09-16 08:04
Thanks for updating us @yuyuxp --- I will close this issue.

**Closed by ttmc** 2018-09-16 08:04 UTC
